[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][ValidateSet('status','plan-update','update','build','search','show','diff')][string]$Command,
  [string]$Root,[string]$SnapshotId,[string]$BaseSnapshotId,[string]$Query,[string]$ObjectType,[string]$Country,[string]$ObjectKey,[switch]$Apply
)
$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'BusinessCentral.Knowledge.ps1');$runtime=Resolve-BCKnowledgeRoot $Root
switch($Command){
  'status' {$lock=Test-BCKnowledgeLock $runtime $SnapshotId;$indexStatus='missing';try{[void](Test-BCKnowledgeIndex $runtime $SnapshotId);$indexStatus='validated'}catch{if($_.Exception.Message-ne'BC_KNOWLEDGE_INDEX_MISSING'){throw}};[ordered]@{status='PASS';snapshot_id=$lock.snapshot_id;bc_version=$lock.bc_version;countries=$lock.countries;index_status=$indexStatus}|ConvertTo-Json -Compress}
  'plan-update' {$registry=Get-BCKnowledgeRegistry;[ordered]@{status='PLANNED';writes_performed=$false;root=$null;sources=@($registry.sources|ForEach-Object{[ordered]@{source_id=$_.source_id;action='inspect-remote';canonical_url=$_.canonical_url}})}|ConvertTo-Json -Depth 5 -Compress}
  'update' {if(-not$Apply){throw 'BC_KNOWLEDGE_UPDATE_APPLY_REQUIRED'};$registry=Get-BCKnowledgeRegistry;New-Item -ItemType Directory -Force -Path (Join-Path $runtime 'sources')|Out-Null;foreach($s in $registry.sources){$mirror=Join-Path $runtime "sources\$($s.source_id).git";if(Test-Path $mirror){if((&git -C $mirror rev-parse --is-bare-repository).Trim()-ne'true'){throw 'BC_KNOWLEDGE_MIRROR_NOT_BARE'};if((&git -C $mirror remote get-url origin).Trim()-ne[string]$s.canonical_url){throw 'BC_KNOWLEDGE_REMOTE_MISMATCH'};&git -C $mirror fetch --prune origin}else{&git clone --mirror $s.canonical_url $mirror};if($LASTEXITCODE-ne0){throw 'BC_KNOWLEDGE_UPDATE_FAILED'}};[ordered]@{status='UPDATED_UNBOUND';writes_performed=$true;scope='shared-cache-only'}|ConvertTo-Json -Compress}
  'build' {if(-not$Apply){throw 'BC_KNOWLEDGE_BUILD_APPLY_REQUIRED'};$m=Build-BCKnowledgeIndex $runtime $SnapshotId;$m|ConvertTo-Json -Depth 8 -Compress}
  'search' {$items=Search-BCKnowledgeIndex $runtime $SnapshotId $Query $ObjectType $Country;@($items)|ConvertTo-Json -Depth 12}
  'show' {if(-not$ObjectKey){throw 'BC_KNOWLEDGE_OBJECT_KEY_REQUIRED'};$items=Search-BCKnowledgeIndex $runtime $SnapshotId $null $null $null;$match=@($items|Where-Object object_key -eq $ObjectKey);if($match.Count-ne1){throw 'BC_KNOWLEDGE_OBJECT_NOT_FOUND'};$match[0]|ConvertTo-Json -Depth 12}
  'diff' {if(-not$BaseSnapshotId){throw 'BC_KNOWLEDGE_BASE_SNAPSHOT_REQUIRED'};[void](Test-BCKnowledgeIndex $runtime $BaseSnapshotId);[void](Test-BCKnowledgeIndex $runtime $SnapshotId);$base=@(Get-Content (Join-Path $runtime "indexes\$BaseSnapshotId\objects.jsonl")|%{ConvertFrom-Json $_});$target=@(Get-Content (Join-Path $runtime "indexes\$SnapshotId\objects.jsonl")|%{ConvertFrom-Json $_});$bm=@{};foreach($o in $base){$bm[$o.object_key]=$o|ConvertTo-Json -Depth 12 -Compress};$tm=@{};foreach($o in $target){$tm[$o.object_key]=$o|ConvertTo-Json -Depth 12 -Compress};$added=@($tm.Keys|?{-not$bm.ContainsKey($_)}|Sort-Object);$removed=@($bm.Keys|?{-not$tm.ContainsKey($_)}|Sort-Object);$changed=@($tm.Keys|?{$bm.ContainsKey($_)-and$bm[$_]-cne$tm[$_]}|Sort-Object);[ordered]@{status='PASS';base_snapshot=$BaseSnapshotId;target_snapshot=$SnapshotId;added=$added;changed=$changed;removed=$removed}|ConvertTo-Json -Depth 6}
}
