[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Destination)
$ErrorActionPreference='Stop';$d=[IO.Path]::GetFullPath($Destination);if(Test-Path $d){throw 'STORY_TARGET_EXISTS'};New-Item -ItemType Directory -Force $d|Out-Null
$offer=[ordered]@{id='OFR-SYNTHETIC-001';version=1;scope='synthetic BC Basic';assumptions=@('synthetic-only');deliverables=@('D-SYN-001');planned_hours=100;planned_cost=10000;actual_hours=95;actual_cost=9500;gates=@('offer-approved','project-start');status='closed'}
$pages=@([ordered]@{id='PAGE-SYN-001';parent=$null;version=1;status='published';author_role='synthetic-editor';time='2026-01-01T09:00:00Z';references=@('OFR-SYNTHETIC-001')},[ordered]@{id='PAGE-SYN-002';parent='PAGE-SYN-001';version=1;status='published';author_role='synthetic-editor';time='2026-01-02T09:00:00Z';references=@('TKT-SYN-001')})
$tickets=@([ordered]@{id='TKT-SYN-001';type='epic';status='done';acceptance=@('scope documented');evidence=@('EVD-SYN-001');comments=@('Closed after synthetic review');worklogs=@([ordered]@{hours=2;role='synthetic'})},[ordered]@{id='TKT-SYN-002';type='bug';status='closed';acceptance=@('retest passed');evidence=@('EVD-SYN-002');comments=@('Retest completed');worklogs=@([ordered]@{hours=1;role='synthetic'})})
$events=@('offer','project-start','planning','setup','migration','sit','uat','training','cutover-go','go-live-rehearsal','hypercare-day-1','hypercare-day-2','handover')|% {[ordered]@{id="STORY-$($_)";kind=$_;time='2026-01-01T09:00:00Z';references=@('OFR-SYNTHETIC-001')}}
$hyper=@([ordered]@{day=1;priority='P2';diagnosis='synthetic';fix='synthetic-fix';retest='passed';status='closed'},[ordered]@{day=2;priority='P3';diagnosis='none';fix='none';retest='passed';status='closed'})
$evidence=@([ordered]@{id='EVD-SYN-001';type='documentation';hash=('a'*64)},[ordered]@{id='EVD-SYN-002';type='test';hash=('b'*64)})
@{offer=$offer;pages=$pages;tickets=$tickets;timeline=$events;hypercare=$hyper;evidence=$evidence}|ConvertTo-Json -Depth 20|Set-Content (Join-Path $d 'project-story.json') -Encoding utf8
@($offer,$pages,$tickets,$events,$hyper,$evidence)|ConvertTo-Json -Depth 20|Set-Content (Join-Path $d 'mapping-export.json') -Encoding utf8;Write-Host 'PASS: Synthetic project story generated.'
