[CmdletBinding()]
param([Parameter(Mandatory)][string]$Destination)
$ErrorActionPreference='Stop';if(Test-Path $Destination){throw 'BC_KNOWLEDGE_DESTINATION_EXISTS'};New-Item -ItemType Directory -Path $Destination|Out-Null
$sources=@(
 [ordered]@{source_id='microsoft-bc-functional-docs';canonical_url='https://github.com/MicrosoftDocs/dynamics365smb-docs.git';title='Business Central functional documentation';publisher='Microsoft';retrieved_at='2026-01-01T00:00:00Z';commit=('a'*40);tree=('b'*40);content_digest=('1'*64);license_id='CC-BY-4.0'},
 [ordered]@{source_id='microsoft-bc-devitpro-docs';canonical_url='https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb.git';title='Business Central developer and IT-Pro documentation';publisher='Microsoft';retrieved_at='2026-01-01T00:00:00Z';commit=('c'*40);tree=('d'*40);content_digest=('2'*64);license_id='CC-BY-4.0'},
 [ordered]@{source_id='microsoft-bcapps';canonical_url='https://github.com/microsoft/BCApps.git';title='Business Central application source';publisher='Microsoft';retrieved_at='2026-01-01T00:00:00Z';commit=('e'*40);tree=('f'*40);content_digest=('3'*64);license_id='MIT'}
)
$areas=@('company','general-setup','finance','vat','posting-groups','dimensions','number-series','purchase','sales','inventory','bank-payments','period-close','vat-preview','permissions','configuration-packages','testing','training','cutover','support')
$items=@();$i=0;foreach($area in $areas){$i++;$items+=[ordered]@{knowledge_id=('KNOW-{0:D3}' -f $i);title=('Synthetischer Startpunkt '+$area);knowledge_kind='official_documented';source_id='microsoft-bc-functional-docs';version='28.2';locale='de-DE';process=$area;role=($(if($area -eq 'support'){'support'}else{'consultant'}));object_refs=@('page:unresolved-from-validated-lock');project_phase=($(if($area -in @('testing','training','cutover')){$area}else{'implementation'}));task_type=($(if($area -eq 'support'){'support'}else{'setup'}));prerequisites=@('validated-source-lock');expected_effect='Nur als gebundene Wissensaussage nutzbar';controls=@('readback-required');error_patterns=@('source-or-version-mismatch');use_case_refs=@(('UC-'+$area.ToUpperInvariant()))}}
$play=@(
 [ordered]@{playthrough_id='PT-COMPANY-PREFLIGHT';title='Company Preflight';mode='plan-only';baseline='existing_validated_company';customer_target='unbound';preconditions=@('environment-bound','role-authorized');steps=@('Version, Locale und Company pruefen');readback=@('Company und Version erneut lesen');error_handling=@('Bei Abweichung stoppen');stop_codes=@('BC_PLAN_BINDING_MISMATCH');direct_mutation=$false},
 [ordered]@{playthrough_id='PT-COMPANY-CREATE';title='Gesellschaft erstellen oder kopieren';mode='plan-only';baseline='microsoft_demo_baseline';customer_target='unbound';preconditions=@('preflight-pass','explicit-human-approval-required-for-future-execution');steps=@('Baseline waehlen','Create-or-copy als Vorschlag planen','kundenspezifisches Soll getrennt erfassen');readback=@('Neue Company separat pruefen','Sollabweichungen dokumentieren');error_handling=@('Nie CRONUS als kundenfertig markieren');stop_codes=@('BC_KNOWLEDGE_CRONUS_NOT_CUSTOMER_READY');direct_mutation=$false},
 [ordered]@{playthrough_id='PT-CONFIG-PACKAGE';title='Konfigurationspaket importieren validieren anwenden';mode='plan-only';baseline='existing_validated_company';customer_target='unbound';preconditions=@('package-classified','backup-planned');steps=@('Importvorschau','Validierung','Apply nur spaeter autorisiert');readback=@('Fehler und Summen vergleichen');error_handling=@('Fehler korrigieren und erneut validieren');stop_codes=@('BC_PLAN_PACKAGE_INVALID');direct_mutation=$false},
 [ordered]@{playthrough_id='PT-READBACK';title='Readback und Evidence';mode='plan-only';baseline='existing_validated_company';customer_target='unbound';preconditions=@('expected-state-defined');steps=@('sichtbaren Zustand lesen','Kontrollen vergleichen');readback=@('Abweichung und Quelle protokollieren');error_handling=@('Unbekannt sichtbar lassen');stop_codes=@('BC_PLAN_READBACK_MISMATCH');direct_mutation=$false},
 [ordered]@{playthrough_id='PT-ERROR';title='Fehlerbehandlung';mode='plan-only';baseline='existing_validated_company';customer_target='unbound';preconditions=@('error-observed');steps=@('Fehler klassifizieren','Stop-Code zuordnen','Retest planen');readback=@('Fehlerzustand erneut lesen');error_handling=@('Keine stille Reparatur');stop_codes=@('BC_PLAN_FAIL_CLOSED');direct_mutation=$false}
)
$root=[ordered]@{schema_version=1;product_id='spectra';knowledge_pack_id='bc-basic-start-synthetic';bc_version='28.2';locale='de-DE';source_locks=$sources;knowledge_items=$items;playthroughs=$play}
[IO.File]::WriteAllText((Join-Path $Destination 'bc-knowledge.json'),($root|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));Write-Output 'PASS: synthetischer BC-Wissenspack erzeugt.'
