[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Destination,
    [Parameter(Mandatory=$true)][ValidateSet('implementation','support-only','mixed')][string]$Profile,
    [ValidatePattern('^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$')][string]$ExpectedBlueprintVersion,
    [ValidatePattern('^[A-Za-z][A-Za-z0-9_-]{1,63}$')][string]$CustomerAlias,
    [string]$ProductRoot,
    [switch]$SyntheticFixture
)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
function Write-Utf8File([string]$Path,[string]$Content){$dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir -PathType Container)){[void](New-Item -ItemType Directory -Path $dir -Force)};[System.IO.File]::WriteAllText($Path,($Content -replace "`r`n","`n"),(New-Object System.Text.UTF8Encoding($false)))}
function New-CrockfordId([string]$Prefix){$alphabet='0123456789ABCDEFGHJKMNPQRSTVWXYZ';$bytes=New-Object byte[] 26;$rng=[System.Security.Cryptography.RandomNumberGenerator]::Create();try{$rng.GetBytes($bytes)}finally{$rng.Dispose()};$chars=for($i=0;$i -lt 26;$i++){$alphabet[[int]$bytes[$i]%$alphabet.Length]};return "$Prefix-$($chars -join '')"}
function Test-NoReparse([string]$Path){$current=[System.IO.Path]::GetFullPath($Path);while($current){if(Test-Path -LiteralPath $current){$item=Get-Item -LiteralPath $current -Force;if(($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint)-ne 0){throw 'DESTINATION_REPARSE_POINT'}};$parent=Split-Path -Parent $current;if($parent -eq $current){break};$current=$parent}}
function Get-VerifiedManifest([string]$Root,[string]$Version){
    if([string]::IsNullOrWhiteSpace($Version)){throw 'VERSION_REQUIRED'};$manifestPath=Join-Path $Root "release\versions\$Version\release-manifest.json";if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){throw 'INSTALLABLE_MANIFEST_MISSING'};$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json
    if([string]$manifest.product_id -ne 'spectra' -or [string]$manifest.release_version -ne $Version -or [string]$manifest.blueprint_version -ne $Version -or [string]$manifest.release_kind -ne 'installable_blueprint' -or [string]$manifest.manifest_state -ne 'final' -or [string]$manifest.consumer_mode -ne 'INSTALLABLE_BLUEPRINT' -or $manifest.installable_blueprint -ne $true -or [string]$manifest.expected_tag -ne "spectra-v$Version" -or [string]$manifest.source_commit -notmatch '^[0-9a-f]{40}$'){throw 'INSTALLABLE_MANIFEST_CONTRACT_INVALID'}
    . (Join-Path $PSScriptRoot 'Release.Common.ps1');$scope=Get-BCProjectOSReleaseScope -Root $Root;$records=@(Get-BCProjectOSGitPayloadRecords -Root $Root -Revision $manifest.source_commit -Scope $scope);$digest=Get-BCProjectOSTextSha256 -Text (Get-BCProjectOSChecksumsText -Records $records);if($digest -ne [string]$manifest.payload.bundle_digest){throw 'INSTALLABLE_MANIFEST_DIGEST_MISMATCH'}
    $remote=@(& git -C $Root remote get-url origin 2>$null);if($LASTEXITCODE -ne 0 -or [string]($remote|Select-Object -First 1) -ne 'https://github.com/sivla/BCProjectOS.git'){throw 'INSTALLABLE_REMOTE_INVALID'};& git -C $Root show-ref --verify --quiet "refs/tags/$($manifest.expected_tag)";if($LASTEXITCODE -ne 0){throw 'INSTALLABLE_TAG_MISSING'};$tagType=& git -C $Root cat-file -t "refs/tags/$($manifest.expected_tag)" 2>$null|Select-Object -First 1;if([string]$tagType -ne 'tag'){throw 'INSTALLABLE_TAG_NOT_ANNOTATED'};$tagCommit=& git -C $Root rev-parse "refs/tags/$($manifest.expected_tag)^{commit}" 2>$null|Select-Object -First 1;if([string]$tagCommit -notmatch '^[0-9a-f]{40}$'){throw 'INSTALLABLE_TAG_COMMIT_INVALID'};& git -C $Root merge-base --is-ancestor $manifest.source_commit $tagCommit 2>$null;if($LASTEXITCODE -ne 0){throw 'INSTALLABLE_SOURCE_ANCESTRY_INVALID'};& git -C $Root cat-file -e "$tagCommit`:release/versions/$Version/release-manifest.json" 2>$null;if($LASTEXITCODE -ne 0){throw 'INSTALLABLE_MANIFEST_NOT_TAGGED'}
    return [pscustomobject]@{manifest=$manifest;tag_commit=[string]$tagCommit}
}
$root=if([string]::IsNullOrWhiteSpace($ProductRoot)){[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))}else{[System.IO.Path]::GetFullPath($ProductRoot)}
if($SyntheticFixture){if($CustomerAlias -or $ExpectedBlueprintVersion){throw 'SYNTHETIC_ARGUMENT_MIXED'}}else{if([string]::IsNullOrWhiteSpace($CustomerAlias)){throw 'CUSTOMER_ALIAS_REQUIRED'};$verified=Get-VerifiedManifest -Root $root -Version $ExpectedBlueprintVersion}
$destinationPath=[System.IO.Path]::GetFullPath($Destination);$parent=Split-Path -Parent $destinationPath;if(-not(Test-Path -LiteralPath $parent -PathType Container)){throw 'DESTINATION_PARENT_MISSING'};Test-NoReparse $parent;if(Test-Path -LiteralPath $destinationPath){throw 'DESTINATION_EXISTS'}
$staging=Join-Path $parent ('.spectra-workspace-'+[Guid]::NewGuid().ToString('N'));$created=$false
try{
 [void](New-Item -ItemType Directory -Path $staging);$created=$true;$dirs=@('governance/catalogs','governance/policies','governance/decisions','company','knowledge/items','knowledge/processes','knowledge/business-rules','knowledge/bc','knowledge/bc/sales','knowledge/bc/purchasing','knowledge/bc/inventory','knowledge/bc/finance','knowledge/application-landscape','projects','support/cases','support/board','meetings','work/tickets','external-files/inbox','external-files/review','external-files/quarantine','external-files/register','external-files/originals','external-files/derived','external-files/processing-log','openspec/schemas','openspec/specs','openspec/changes','evidence','generated','automation','schemas','migrations','backup/manifests');foreach($dir in $dirs){[void](New-Item -ItemType Directory -Path (Join-Path $staging $dir) -Force)};foreach($catalog in Get-ChildItem -LiteralPath (Join-Path $root 'catalogs') -File|Sort-Object Name){Copy-Item -LiteralPath $catalog.FullName -Destination (Join-Path $staging 'governance\catalogs')};Write-Utf8File (Join-Path $staging 'governance\policies\workspace-profile.yaml') (([ordered]@{schema_version=1;profile=$Profile}|ConvertTo-Json)+"`n");Write-Utf8File (Join-Path $staging 'openspec\config.yaml') "schema: spec-driven`n";Write-Utf8File (Join-Path $staging '.gitignore') "external-files/originals/`n";foreach($area in @('sales','purchasing','inventory','finance')){Write-Utf8File (Join-Path $staging "knowledge\bc\$area\README.md") "# $area`n`nEs wurde kein Kundenwissen erfasst.`n"}
 if($SyntheticFixture){$meta=[ordered]@{schema_version=1;artifact_type='bcprojectos_synthetic_workspace_fixture';fixture_id=(New-CrockfordId 'TFX');product_id='spectra';synthetic=$true;installable=$false;release_status='PENDING_BCPROJECTOS_RELEASE';profile=$Profile;created_at=[DateTime]::UtcNow.ToString('o');openspec_roots=@('openspec')};Write-Utf8File (Join-Path $staging 'synthetic-fixture.yaml') (($meta|ConvertTo-Json -Depth 5)+"`n");Write-Utf8File (Join-Path $staging 'README.md') "# Synthetische Spectra-Fixture`n`nNicht installierbar. Keine Kundeninstanz.`n";& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'Test-SyntheticWorkspaceFixture.ps1') -Path $staging;if($LASTEXITCODE -ne 0){throw 'SYNTHETIC_VALIDATION_FAILED'}}
 else{$id=New-CrockfordId 'CUS';$workspace=[ordered]@{schema_version=1;id=$id;customer_id=$id;entity_type='customer';title=$CustomerAlias;lifecycle_status='draft';created_at=[DateTime]::UtcNow.ToString('o');relations=@();blueprint_id='bcprojectos';blueprint_version=$ExpectedBlueprintVersion;created_with_version=$ExpectedBlueprintVersion;last_migrated_at=$null;openspec_roots=@('openspec')};Write-Utf8File (Join-Path $staging 'workspace.yaml') (($workspace|ConvertTo-Json -Depth 5)+"`n");$bind=[ordered]@{schema_version=1;binding_status='BOUND';product_id='spectra';repository_url='https://github.com/sivla/BCProjectOS.git';release_version=$ExpectedBlueprintVersion;release_tag="spectra-v$ExpectedBlueprintVersion";tag_commit=$verified.tag_commit;manifest_path="release/versions/$ExpectedBlueprintVersion/release-manifest.json";manifest_source_commit=$verified.manifest.source_commit;consumer_mode='INSTALLABLE_BLUEPRINT';installable_blueprint=$true;digest_algorithm='SHA-256';payload_bundle_digest=[string]$verified.manifest.payload.bundle_digest};Write-Utf8File (Join-Path $staging 'governance\policies\release-binding.json') (($bind|ConvertTo-Json -Depth 5)+"`n");Write-Utf8File (Join-Path $staging 'AGENTS.md') "# Spectra Kundenworkspace`n`nKeine vorerfassten Kundenfakten.`n";Write-Utf8File (Join-Path $staging 'README.md') "# Spectra Kundenworkspace`n`nAlias: $CustomerAlias`n";Write-Host "PASS: Created verified installable Spectra workspace at $destinationPath"}
 Move-Item -LiteralPath $staging -Destination $destinationPath;$created=$false
}finally{if($created -and (Test-Path -LiteralPath $staging -PathType Container)){Remove-Item -LiteralPath $staging -Recurse -Force}}
