[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Destination,[ValidateSet('implementation','support-only')][string]$Profile='implementation')
$ErrorActionPreference='Stop';$d=[IO.Path]::GetFullPath($Destination);if(Test-Path $d){throw 'UAT_DESTINATION_EXISTS'};New-Item -ItemType Directory $d|Out-Null
$roles=@([ordered]@{id='ROLE-PROCESS-OWNER';name='Fachlicher Process Owner';responsibility='UAT-Ergebnis und Abweichung entscheiden'},[ordered]@{id='ROLE-KEY-USER';name='Key User';responsibility='Tests und rollenspezifische Übungen durchführen'},[ordered]@{id='ROLE-TEST-LEAD';name='Test Lead';responsibility='Abdeckung, Triage, Evidence und Exit koordinieren'})
$evidence=@(
 [ordered]@{id='EVD-UAT-BASE';type='uat_result';sha256=('a'*64);synthetic=$true;external_activity=$false},
 [ordered]@{id='EVD-FIX-001';type='fix';sha256=('b'*64);synthetic=$true;external_activity=$false},
 [ordered]@{id='EVD-RETEST-001';type='retest';sha256=('c'*64);synthetic=$true;external_activity=$false},
 [ordered]@{id='EVD-TRAIN-001';type='training_competency';sha256=('d'*64);synthetic=$true;external_activity=$false},
 [ordered]@{id='EVD-SMOKE-001';type='operator_smoke';sha256=('e'*64);synthetic=$true;external_activity=$false})
$decisions=@([ordered]@{id='DEC-UAT-EXIT';type='uat_exit';outcome='GO';reason='Alle Kernprozesse belegt und keine offenen P1/P2';evidence_refs=@('EVD-UAT-BASE','EVD-RETEST-001')},[ordered]@{id='DEC-WAIVER-001';type='waiver';outcome='ACCEPTED';reason='Synthetische P3-Abweichung mit dokumentierter Auswirkung';evidence_refs=@('EVD-UAT-BASE')})
$processes=@('finance','p2p','o2c','cash_bank','inventory','month_end','vat_preview');$tests=@();$n=1;foreach($p in $processes){$tests+=,[ordered]@{id="TC-$($p.ToUpperInvariant()-replace'_','-')-POS";process=$p;path_type='positive';title="$p Standardpfad";preconditions=@('Setup und synthetische Stammdaten sind freigegeben');steps=@('Rolle öffnet den Prozess','Synthetischen Vorgang ausführen','Ergebnis read-only prüfen');expected_result='Fachliches Soll ist nachvollziehbar';role_ref='ROLE-KEY-USER';owner_role='ROLE-PROCESS-OWNER';evidence_refs=@('EVD-UAT-BASE');decision_refs=@();deviation='none';status='passed'};$n++}
$tests+=,[ordered]@{id='TC-O2C-NEG';process='o2c';path_type='negative';title='Pflichtfeld fehlt';preconditions=@('Synthetischer Beleg');steps=@('Pflichtwert entfernen','Validierung ausführen');expected_result='Buchung wird kontrolliert abgelehnt';role_ref='ROLE-KEY-USER';owner_role='ROLE-PROCESS-OWNER';evidence_refs=@('EVD-UAT-BASE');decision_refs=@();deviation='none';status='passed'}
$tests+=,[ordered]@{id='TC-BANK-EXC';process='cash_bank';path_type='exception';title='Nicht zuordenbare Bankzeile';preconditions=@('Synthetische Bankzeile');steps=@('Zuordnung simulieren','Eskalationsweg prüfen');expected_result='Ausnahme bleibt transparent';role_ref='ROLE-KEY-USER';owner_role='ROLE-PROCESS-OWNER';evidence_refs=@('EVD-UAT-BASE');decision_refs=@('DEC-WAIVER-001');deviation='accepted_exception';status='passed'}
$tests+=,[ordered]@{id='TC-FIN-RETEST';process='finance';path_type='retest';title='Retest nach Korrektur';preconditions=@('Fix-Evidence liegt vor');steps=@('Ursprungsschritte wiederholen','Soll und Ist vergleichen');expected_result='Fehler ist nicht reproduzierbar';role_ref='ROLE-KEY-USER';owner_role='ROLE-TEST-LEAD';evidence_refs=@('EVD-RETEST-001');decision_refs=@();deviation='defect';status='passed'}
$training=@();foreach($r in $roles){$suffix=$r.id-replace'^ROLE-','';$training+=,[ordered]@{id="TRN-$suffix";role_ref=$r.id;learning_objectives=@('Relevante BC-Basic-Aufgabe sicher erklären und durchführen');exercises=@('Synthetischen Standardfall durchführen');failure_scenarios=@('Fehlenden Wert erkennen und eskalieren');competency_evidence_ref='EVD-TRAIN-001';operator_smoke='Anmelden, Aufgabe finden, Ergebnis prüfen und sicher abbrechen';escalation_path='Test Lead und Process Owner informieren';status='competent'}}
$defects=@(
 [ordered]@{id='DEF-FIN-001';test_ref='TC-FIN-RETEST';title='Synthetische Buchungsabweichung';reproduction_steps=@('Testfall öffnen','Synthetische Eingabe verwenden','Abweichung beobachten');priority='P2';severity='high';triage='Fix vor Exit erforderlich';owner_role='ROLE-TEST-LEAD';status='closed';status_history=@([ordered]@{status='new';time='2030-03-01T09:00:00Z';role_ref='ROLE-KEY-USER'},[ordered]@{status='triaged';time='2030-03-01T10:00:00Z';role_ref='ROLE-TEST-LEAD'},[ordered]@{status='fixed';time='2030-03-02T09:00:00Z';role_ref='ROLE-TEST-LEAD'},[ordered]@{status='retest';time='2030-03-02T11:00:00Z';role_ref='ROLE-KEY-USER'},[ordered]@{status='closed';time='2030-03-02T12:00:00Z';role_ref='ROLE-PROCESS-OWNER'});fix_evidence_refs=@('EVD-FIX-001');retest_evidence_refs=@('EVD-RETEST-001');waiver_decision_ref=$null},
 [ordered]@{id='DEF-BANK-001';test_ref='TC-BANK-EXC';title='Synthetische Ausnahme akzeptiert';reproduction_steps=@('Ausnahmefall öffnen','Auswirkung prüfen');priority='P3';severity='medium';triage='Waiver fachlich bewerten';owner_role='ROLE-PROCESS-OWNER';status='waived';status_history=@([ordered]@{status='new';time='2030-03-03T09:00:00Z';role_ref='ROLE-KEY-USER'},[ordered]@{status='triaged';time='2030-03-03T10:00:00Z';role_ref='ROLE-TEST-LEAD'},[ordered]@{status='waived';time='2030-03-03T12:00:00Z';role_ref='ROLE-PROCESS-OWNER'});fix_evidence_refs=@();retest_evidence_refs=@();waiver_decision_ref='DEC-WAIVER-001'})
$x=[ordered]@{schema_version=1;product_id='spectra';profile=$Profile;program_id="SYN-UAT-$($Profile.ToUpperInvariant())";roles=$roles;uat_plan=[ordered]@{id='UAT-PLAN-CORE';entry_criteria=@('Setup- und Daten-Dry-run sind freigegeben','Testrollen sind benannt');exit_criteria=@('Alle Kernprozesse belegt','Keine offenen P1/P2','Kompetenznachweise vorhanden');required_processes=$processes;owner_role='ROLE-TEST-LEAD';evidence_refs=@('EVD-UAT-BASE');simulation_boundary='synthetic_non_production'};test_cases=$tests;training_paths=$training;defects=$defects;evidence=$evidence;decisions=$decisions;exit_gate=[ordered]@{decision_ref='DEC-UAT-EXIT';open_p1=0;open_p2=0;all_required_processes_covered=$true;training_complete=$true;status='GO'}}
$utf8=New-Object Text.UTF8Encoding($false);[IO.File]::WriteAllText((Join-Path $d 'uat-training-defects.json'),(($x|ConvertTo-Json -Depth 30)+"`n"),$utf8);Write-Host "PASS: Synthetisches UAT-/Training-/Defect-Profil $Profile wurde deterministisch erzeugt."
