[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Destination)
$ErrorActionPreference='Stop'; $d=[IO.Path]::GetFullPath($Destination)
if(Test-Path $d){throw 'HARDENING_TARGET_EXISTS'}
New-Item -ItemType Directory -Force (Join-Path $d 'pages')|Out-Null
Set-Content (Join-Path $d 'pages/home.md') '# Synthetische Projektstory' -Encoding utf8
Set-Content (Join-Path $d 'pages/uat.md') '# Synthetische UAT' -Encoding utf8
$c1=[ordered]@{id='COM-HARD-001';time='2026-01-03T10:00:00Z';author_role='synthetic';type='working';text='Working';evidence=@()}
$c2=[ordered]@{id='COM-HARD-002';time='2026-01-04T10:00:00Z';author_role='synthetic';type='closing';text='Closed after retest';evidence=@('EVD-HARD-001')}
$base=[ordered]@{reporter='synthetic';assignee='synthetic';priority='P2';parent='TKT-HARD-EPIC';dependencies=@();labels=@('synthetic');components=@('BC');created='2026-01-02T10:00:00Z';acceptance=@('retest passed');evidence=@('EVD-HARD-001');status_history=@([ordered]@{status='open';time='2026-01-02T10:00:00Z'},[ordered]@{status='done';time='2026-01-04T10:00:00Z'});comments=@($c1,$c2)}
$t1=[ordered]@{id='TKT-HARD-001';type='bug';summary='Synthetic P2 bug';description='Synthetic';worklogs=@([ordered]@{id='WL-HARD-001';date='2026-01-03';role='synthetic';hours=6;activity='fix';phase='test';cost=600})}+ $base
$t2=[ordered]@{id='TKT-HARD-002';type='task';summary='Synthetic P3 task';description='Synthetic';worklogs=@([ordered]@{id='WL-HARD-002';date='2026-01-03';role='synthetic';hours=3;activity='test';phase='uat';cost=300})}+ $base
$story=[ordered]@{offer=[ordered]@{id='OFR-HARD-001';version=1;scope='synthetic';assumptions=@('synthetic');deliverables=@('D-HARD-001');planned_hours=10;planned_cost=1000;actual_hours=9;actual_cost=900;gates=@('approval')};pages=@([ordered]@{id='PAGE-HARD-001';sourcePath='pages/home.md';parent=$null;version=1;status='published';author_role='synthetic';time='2026-01-01T09:00:00Z';title='Home';references=@('OFR-HARD-001')},[ordered]@{id='PAGE-HARD-002';sourcePath='pages/uat.md';parent='PAGE-HARD-001';version=1;status='published';author_role='synthetic';time='2026-01-02T09:00:00Z';title='UAT';references=@('TKT-HARD-001')});tickets=@($t1,$t2);timeline=@([ordered]@{id='EV-HARD-001';time='2026-01-01T09:00:00Z';phase='offer';role='synthetic';references=@('OFR-HARD-001','PAGE-HARD-001');state='open';action='offer';result='accepted';decision='GO';nextStep='uat';evidence=@('EVD-HARD-001')},[ordered]@{id='EV-HARD-002';time='2026-01-04T12:00:00Z';phase='uat';role='synthetic';references=@('TKT-HARD-001','PAGE-HARD-002');state='closed';action='test';result='passed';decision='GO';nextStep='handover';evidence=@('EVD-HARD-001')});hypercare=@(1,2,3|% {[ordered]@{day=$_;daily_page='PAGE-HARD-002';tickets=@('TKT-HARD-001');priority='P2';diagnosis='synthetic';fix='synthetic';retest='passed';trend='stable';nextDay='continue';go_no_go='GO';status='closed'}});evidence=@([ordered]@{id='EVD-HARD-001';hash=('c'*64);type='test'});graph=@([ordered]@{from='OFR-HARD-001';to='PAGE-HARD-001';type='offer-page'},[ordered]@{from='PAGE-HARD-001';to='OFR-HARD-001';type='page-offer'},[ordered]@{from='PAGE-HARD-001';to='TKT-HARD-001';type='page-ticket'},[ordered]@{from='TKT-HARD-001';to='PAGE-HARD-001';type='ticket-page'},[ordered]@{from='TKT-HARD-001';to='EVD-HARD-001';type='ticket-evidence'},[ordered]@{from='EVD-HARD-001';to='TKT-HARD-001';type='evidence-ticket'})};$story|ConvertTo-Json -Depth 30|Set-Content (Join-Path $d 'project-story.json') -Encoding utf8;Write-Host 'PASS: Hardened synthetic project story generated.'
