[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$WorkspacePath,
 [Parameter(Mandatory=$true)][ValidatePattern('^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$')][string]$TargetVersion,
 [Parameter(Mandatory=$true)][string]$ProductRoot,
 [string]$PlanPath,
 [switch]$Apply,
 [switch]$Approve
)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
function Write-JsonFile([string]$Path,$Object){$tmp="$Path.$([Guid]::NewGuid().ToString('N')).tmp";[System.IO.File]::WriteAllText($tmp,(($Object|ConvertTo-Json -Depth 20)+"`n"),(New-Object System.Text.UTF8Encoding($false)));Move-Item $tmp $Path -Force}
function Compare-Version([string]$A,[string]$B){$ma=[regex]::Match($A,'^(\d+)\.(\d+)\.(\d+)(?:-alpha\.(\d+))?$');$mb=[regex]::Match($B,'^(\d+)\.(\d+)\.(\d+)(?:-alpha\.(\d+))?$');if(-not $ma.Success -or -not $mb.Success){throw 'VERSION_COMPARISON_UNSUPPORTED'};foreach($i in 1..3){if([int]$ma.Groups[$i].Value -ne [int]$mb.Groups[$i].Value){return [Math]::Sign(([int]$ma.Groups[$i].Value)-([int]$mb.Groups[$i].Value))}};$pa=if($ma.Groups[4].Success){[int]$ma.Groups[4].Value}else{[int]::MaxValue};$pb=if($mb.Groups[4].Success){[int]$mb.Groups[4].Value}else{[int]::MaxValue};return [Math]::Sign($pa-$pb)}
$bindingPath=Join-Path $WorkspacePath 'governance\policies\release-binding.json';$workspaceFile=Join-Path $WorkspacePath 'workspace.yaml';if(-not(Test-Path $bindingPath)-or-not(Test-Path $workspaceFile)){throw 'WORKSPACE_METADATA_MISSING'};$source=Get-Content $bindingPath -Raw|ConvertFrom-Json;$ws=Get-Content $workspaceFile -Raw|ConvertFrom-Json
if([string]$source.binding_status-ne 'BOUND'){throw 'SOURCE_BINDING_NOT_BOUND'};$versionRelation=Compare-Version ([string]$source.release_version) $TargetVersion;if($versionRelation -gt 0){throw 'DOWNGRADE_NOT_ALLOWED'}
$targetManifestPath=Join-Path $ProductRoot "release\versions\$TargetVersion\release-manifest.json";if(-not(Test-Path $targetManifestPath)){throw 'TARGET_MANIFEST_MISSING'};$target=Get-Content $targetManifestPath -Raw|ConvertFrom-Json;if([string]$target.manifest_state-ne 'final'-or[string]$target.product_id-ne 'spectra'-or[string]$target.consumer_mode-ne 'INSTALLABLE_BLUEPRINT'-or$target.installable_blueprint-ne $true){throw 'TARGET_RELEASE_NOT_FINAL_BOUND'}
& git -C $ProductRoot show-ref --verify --quiet "refs/tags/$($target.expected_tag)";if($LASTEXITCODE-ne 0){throw 'TARGET_TAG_MISSING'};$tagType=((& git -C $ProductRoot cat-file -t "refs/tags/$($target.expected_tag)")|Select-Object -First 1);if($tagType-ne 'tag'){throw 'TARGET_TAG_NOT_ANNOTATED'};$tagCommit=((& git -C $ProductRoot rev-parse "refs/tags/$($target.expected_tag)^{commit}")|Select-Object -First 1);if([string]$tagCommit -notmatch '^[0-9a-f]{40}$'){throw 'TARGET_TAG_COMMIT_INVALID'};& git -C $ProductRoot merge-base --is-ancestor ([string]$target.source_commit) ([string]$tagCommit);if($LASTEXITCODE-ne 0){throw 'TARGET_SOURCE_NOT_ANCESTRAL'}
. (Join-Path $PSScriptRoot 'Release.Common.ps1');$scope=Get-BCProjectOSReleaseScope -Root $ProductRoot;$targetRecords=@(Get-BCProjectOSGitPayloadRecords -Root $ProductRoot -Revision 'HEAD' -Scope $scope);$targetDigest=Get-BCProjectOSTextSha256 (Get-BCProjectOSChecksumsText $targetRecords);if($targetDigest-ne [string]$target.payload.bundle_digest){throw 'TARGET_DIGEST_MISMATCH'}
$conflicts=New-Object System.Collections.ArrayList;$catalogSource=Join-Path $ProductRoot 'catalogs';foreach($catalog in Get-ChildItem (Join-Path $WorkspacePath 'governance\catalogs') -File){$sourceCatalog=Join-Path $catalogSource $catalog.Name;if(-not(Test-Path $sourceCatalog)-or((Get-FileHash $catalog.FullName).Hash -ne (Get-FileHash $sourceCatalog).Hash)){[void]$conflicts.Add([ordered]@{code='MANAGED_CATALOG_DRIFT';path="governance/catalogs/$($catalog.Name)";resolution='manual-decision-required'})}}
$status=if($conflicts.Count -gt 0){'BLOCKED'}elseif($versionRelation -eq 0){'NOOP'}else{'PLANNED'};$plan=[ordered]@{schema_version=1;plan_status=$status;dry_run=(-not $Apply);source_binding=[ordered]@{release_version=$source.release_version;release_tag=$source.release_tag;tag_commit=$source.tag_commit;payload_bundle_digest=$source.payload_bundle_digest};target_binding=[ordered]@{release_version=$TargetVersion;release_tag=$target.expected_tag;tag_commit=[string]$tagCommit;manifest_source_commit=$target.source_commit;payload_bundle_digest=$target.payload.bundle_digest};changes=@([ordered]@{path='workspace.yaml';action=if($status -eq 'NOOP'){'no-change'}else{'update-managed-fields'};decision='automatic'},[ordered]@{path='governance/policies/release-binding.json';action=if($status -eq 'NOOP'){'no-change'}else{'update-managed-fields'};decision='automatic'});conflicts=@($conflicts);manual_decisions=@()}
if($PlanPath){Write-JsonFile $PlanPath $plan};if($conflicts.Count -gt 0){throw 'UPGRADE_CONFLICTS_PRESENT'};if(-not $Apply){Write-Host 'PASS: Upgrade dry-run plan created.';return};if(-not $Approve){throw 'EXPLICIT_APPROVAL_REQUIRED'};if($status-eq 'NOOP'){Write-Host 'PASS: Upgrade is already applied.';return}
$ws.blueprint_version=$TargetVersion;$ws.created_with_version=$TargetVersion;$newBinding=[ordered]@{schema_version=1;binding_status='BOUND';product_id='spectra';repository_url=$source.repository_url;release_version=$TargetVersion;release_tag=$target.expected_tag;tag_commit=[string]$tagCommit;manifest_source_commit=$target.source_commit;consumer_mode='INSTALLABLE_BLUEPRINT';installable_blueprint=$true;digest_algorithm='SHA-256';payload_bundle_digest=$target.payload.bundle_digest};Write-JsonFile $workspaceFile $ws;Write-JsonFile $bindingPath $newBinding;$plan.plan_status='APPLIED';$plan.dry_run=$false;if($PlanPath){Write-JsonFile $PlanPath $plan};Write-Host 'PASS: Workspace upgrade applied without touching customer-owned files.'
