Set-StrictMode -Version 2.0

function Get-SpectraBootstrapProductRoot { [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')) }
function Write-SpectraBootstrapJson([string]$Path,$Value){$p=Split-Path -Parent $Path;if([string]::IsNullOrWhiteSpace($p)){$p=(Get-Location).Path};if(-not(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null};$tmp="$Path.tmp";[IO.File]::WriteAllText($tmp,(($Value|ConvertTo-Json -Depth 30)+"`n"),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $Path -Force}
function Read-SpectraBootstrapJson([string]$Path){if(-not(Test-Path $Path -PathType Leaf)){throw 'BOOTSTRAP_FILE_MISSING'};try{Get-Content $Path -Raw|ConvertFrom-Json}catch{throw 'BOOTSTRAP_JSON_INVALID'}}
function Get-SpectraBootstrapSha([string]$Path){(Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Get-SpectraPlatform {if([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT){'windows'}elseif((Get-Variable IsMacOS -ErrorAction SilentlyContinue)-and$IsMacOS){'macos'}else{'other'}}
function Get-SpectraDefaultRoots {
  param([string]$HomePath=$HOME,[string]$XdgConfigHome=$env:XDG_CONFIG_HOME,[string]$XdgDataHome=$env:XDG_DATA_HOME,[string]$Platform=(Get-SpectraPlatform))
  if($Platform -eq 'macos'){
    if([string]::IsNullOrWhiteSpace($HomePath)){throw 'BOOTSTRAP_HOME_MISSING'}
    $homeRoot=$HomePath.TrimEnd('/');$configBase=if($XdgConfigHome){$XdgConfigHome.TrimEnd('/')}else{"$homeRoot/.config"};$dataBase=if($XdgDataHome){$XdgDataHome.TrimEnd('/')}else{"$homeRoot/.local/share"}
    return [ordered]@{config_root="$configBase/spectra";registry_root="$dataBase/spectra";source='xdg'}
  }
  $base=if($env:LOCALAPPDATA){$env:LOCALAPPDATA}elseif($HomePath){Join-Path $HomePath 'AppData\Local'}else{throw 'BOOTSTRAP_HOME_MISSING'}
  [ordered]@{config_root=(Join-Path $base 'Spectra\config');registry_root=(Join-Path $base 'Spectra\data');source='windows-local-app-data'}
}
function Assert-SpectraToolAvailable([string]$Name,[string]$Code='BOOTSTRAP_TOOL_MISSING'){if(-not(Get-Command $Name -ErrorAction SilentlyContinue)){throw "$Code`:$Name"};$true}
function Test-SpectraCanonicalRepositoryUrl([string]$Remote){
  if([string]::IsNullOrWhiteSpace($Remote)){return $false}
  $normalized=$Remote.Trim()
  return $normalized-ceq'https://github.com/sivla/BCProjectOS'-or$normalized-ceq'https://github.com/sivla/BCProjectOS.git'
}
function Test-SpectraRootWritableMetadata([string]$Path){if(-not(Test-Path $Path -PathType Container)){return $false};$item=Get-Item $Path -Force;if(($item.Attributes -band [IO.FileAttributes]::ReadOnly) -ne 0){return $false};$probe=Join-Path $Path ('.spectra-write-probe-'+[guid]::NewGuid().ToString('N'));try{$stream=[IO.File]::Open($probe,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$stream.Dispose();Remove-Item -LiteralPath $probe -Force;return $true}catch{if(Test-Path $probe){Remove-Item -LiteralPath $probe -Force -ErrorAction SilentlyContinue};return $false}}
function Assert-SpectraPortableConfigFile([string]$Path){
  $value=Read-SpectraBootstrapJson $Path
  function Visit($Node,[string]$At){
    if($null-eq$Node){return};if($Node-is[string]){if($Node-match'(?i)Bearer\s+|api[_-]?token\s*[:=]|password\s*[:=]'){throw 'BOOTSTRAP_SECRET_LEAK'};return}
    if($Node-is[Collections.IEnumerable]-and$Node-isnot[string]-and$Node-isnot[pscustomobject]){foreach($item in $Node){Visit $item $At};return}
    foreach($p in @($Node.PSObject.Properties)){if($p.Name-match'^(?i:token|password|secret|auth_state|browser_profile)$'){throw 'BOOTSTRAP_SECRET_LEAK'};if($p.Name-eq'runtime_secret_keys'){foreach($key in @($p.Value)){if([string]$key-cnotmatch'^SPECTRA_[A-Z0-9_]+$'){throw 'BOOTSTRAP_SECRET_REFERENCE_INVALID'}};continue};Visit $p.Value "$At.$($p.Name)"}
  }
  Visit $value 'root';$true
}
function Test-SpectraPathPrefix([string]$Root,[string]$Path,[string]$Platform=(Get-SpectraPlatform)) {
  $comparison = if ($Platform -eq 'windows') { [StringComparison]::OrdinalIgnoreCase } else { [StringComparison]::Ordinal }
  $separator = if ($Root.Contains('/')) { '/' } else { [IO.Path]::DirectorySeparatorChar }
  $prefix = $Root.TrimEnd('/','\') + $separator
  return $Path.StartsWith($prefix, $comparison)
}
function ConvertTo-SpectraRelativePath([string]$Root,[string]$Path,[string]$Platform=(Get-SpectraPlatform)){
  $r=[IO.Path]::GetFullPath($Root).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);$p=[IO.Path]::GetFullPath($Path)
  $prefix=$r+[IO.Path]::DirectorySeparatorChar;if(-not(Test-SpectraPathPrefix -Root $r -Path $p -Platform $Platform)){throw 'BOOTSTRAP_PATH_OUTSIDE_REGISTRY'}
  $relative=$p.Substring($prefix.Length)-replace'\\','/';if([string]::IsNullOrWhiteSpace($relative)-or$relative-match'(^|/)\.\.(/|$)' -or $relative-match'^[A-Za-z]:'){throw 'BOOTSTRAP_PATH_UNSAFE'};$relative
}
function Assert-SpectraNoLinkPath([string]$Root,[string]$Path){
  $current=[IO.Path]::GetFullPath($Path);$rootFull=[IO.Path]::GetFullPath($Root)
  while($current.Length-ge$rootFull.Length){if(Test-Path $current){$item=Get-Item $current -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'BOOTSTRAP_REPARSE_PATH_FORBIDDEN'}};if($current-eq$rootFull){break};$current=Split-Path -Parent $current}
}
function Test-SpectraBootstrapSchema($Value,[string]$Name){$root=Get-SpectraBootstrapProductRoot;. (Join-Path $root 'automation\Spectra.JsonSchema.ps1');$schema=Get-Content (Join-Path $root "schemas\$Name") -Raw|ConvertFrom-Json;$jsonValue=($Value|ConvertTo-Json -Depth 40 -Compress)|ConvertFrom-Json;try{Test-SpectraJsonSchema -Value $jsonValue -Schema $schema -RootSchema $schema -Path root}catch{throw "BOOTSTRAP_SCHEMA_INVALID:$($_.Exception.Message.Split([Environment]::NewLine)[0])"}}
function Get-SpectraReleaseBinding([string]$ProductRoot,[string]$Version){
  $manifestPath=Join-Path $ProductRoot "release\versions\$Version\release-manifest.json";if(-not(Test-Path $manifestPath)){throw 'BOOTSTRAP_RELEASE_MANIFEST_MISSING'};$m=Read-SpectraBootstrapJson $manifestPath
  if($m.manifest_state-ne'final'-or-not$m.installable_blueprint-or$m.consumer_mode-ne'INSTALLABLE_BLUEPRINT'){throw 'BOOTSTRAP_RELEASE_NOT_INSTALLABLE'}
  $installedMarkerPath=Join-Path $ProductRoot '.spectra-install.json';if(Test-Path $installedMarkerPath -PathType Leaf){$marker=Read-SpectraBootstrapJson $installedMarkerPath;if([string]$marker.version-cne$Version-or[string]$marker.release_commit-notmatch'^[a-f0-9]{40}$'-or[string]$marker.release_tree-cne[string]$m.source_tree-or[string]$marker.bundle_digest-cne[string]$m.payload.bundle_digest-or[int]$marker.file_count-ne[int]$m.payload.file_count){throw 'BOOTSTRAP_INSTALLED_RELEASE_MARKER_INVALID'};. (Join-Path $ProductRoot 'automation\Release.Common.ps1');$modeBound=[int]$m.schema_version-ge4;$text=Get-BCProjectOSChecksumsText -Records @($m.payload.files) -IncludeMode:$modeBound;$digest=Get-BCProjectOSTextSha256 $text;if($digest-cne[string]$m.payload.bundle_digest){throw 'BOOTSTRAP_INSTALLED_MANIFEST_DIGEST_INVALID'};foreach($file in @($m.payload.files)){$path=Join-Path $ProductRoot (([string]$file.path)-replace'/',[IO.Path]::DirectorySeparatorChar);if(-not(Test-Path $path -PathType Leaf)-or(Get-SpectraBootstrapSha $path)-cne[string]$file.sha256){throw 'BOOTSTRAP_INSTALLED_PAYLOAD_INVALID'}};return [ordered]@{version=$Version;tag="spectra-v$Version";commit=[string]$marker.release_commit;tree=[string]$marker.release_tree;digest=[string]$marker.bundle_digest}}
  $remote = [string](& git -C $ProductRoot remote get-url origin 2>$null | Select-Object -First 1)
  $remote = $remote.Trim()
  if (-not(Test-SpectraCanonicalRepositoryUrl $remote)) { throw 'BOOTSTRAP_RELEASE_REMOTE_INVALID' }
  $tag="spectra-v$Version";$tagType=(& git -C $ProductRoot cat-file -t "refs/tags/$tag" 2>$null|Select-Object -First 1);if($tagType-cne'tag'){throw 'BOOTSTRAP_RELEASE_TAG_NOT_ANNOTATED'};$peeled=(& git -C $ProductRoot rev-parse "$tag^{}" 2>$null);if($LASTEXITCODE-ne0){throw 'BOOTSTRAP_RELEASE_TAG_BINDING_INVALID'};& git -C $ProductRoot merge-base --is-ancestor ([string]$m.source_commit) ([string]$peeled);if($LASTEXITCODE-ne0){throw 'BOOTSTRAP_RELEASE_TAG_BINDING_INVALID'}
  $sourceTree=(& git -C $ProductRoot rev-parse "$($m.source_commit)^{tree}" 2>$null).Trim();if($LASTEXITCODE-ne0-or$sourceTree-cne[string]$m.source_tree){throw 'BOOTSTRAP_RELEASE_SOURCE_TREE_INVALID'}
  . (Join-Path $ProductRoot 'automation\Release.Common.ps1');$scope=Get-BCProjectOSReleaseScope -Root $ProductRoot -Revision ([string]$m.source_commit);$modeBound=[int]$m.schema_version-ge4;$records=@(Get-BCProjectOSGitPayloadRecords -Root $ProductRoot -Revision ([string]$m.source_commit) -Scope $scope -IncludeMode:$modeBound);$text=Get-BCProjectOSChecksumsText $records -IncludeMode:$modeBound;$digest=Get-BCProjectOSTextSha256 $text
  if($records.Count-ne[int]$m.payload.file_count-or$digest-cne[string]$m.payload.bundle_digest){throw 'BOOTSTRAP_RELEASE_PAYLOAD_DIGEST_INVALID'}
  [ordered]@{version=$Version;tag=$tag;commit=[string]$peeled;tree=[string]$m.source_tree;digest=[string]$m.payload.bundle_digest}
}
function Initialize-SpectraProjectRegistry([string]$RegistryRoot,[string]$ObservedAt,[switch]$Apply){$root=[IO.Path]::GetFullPath($RegistryRoot);if(Test-Path $root){if(-not(Test-Path $root -PathType Container)){throw 'BOOTSTRAP_REGISTRY_ROOT_INVALID'}}elseif(-not$Apply){return [ordered]@{status='PLANNED';writes_performed=$false;registry_root=$root}}else{$parent=Split-Path -Parent $root;if(-not(Test-Path $parent -PathType Container)){throw 'BOOTSTRAP_REGISTRY_PARENT_MISSING'};New-Item -ItemType Directory -Path $root|Out-Null};$path=Join-Path $root 'spectra-projects.json';if(Test-Path $path){$registry=Read-SpectraBootstrapJson $path;Test-SpectraProjectRegistry $registry|Out-Null;return [ordered]@{status='ALREADY_INITIALIZED';writes_performed=$false;registry_root=$root}};if(-not$Apply){return [ordered]@{status='PLANNED';writes_performed=$false;registry_root=$root}};$registry=[ordered]@{schema_version=1;product_id='spectra';registry_id='REG-LOCAL-SPECTRA';created_at=$ObservedAt;entries=@()};Test-SpectraProjectRegistry $registry|Out-Null;Write-SpectraBootstrapJson $path $registry;[ordered]@{status='INITIALIZED';writes_performed=$true;registry_root=$root}}
function Initialize-SpectraBootstrapRoots([string]$ConfigRoot,[string]$RegistryRoot,[string]$ObservedAt,[switch]$Apply){
  $config=[IO.Path]::GetFullPath($ConfigRoot);$registry=[IO.Path]::GetFullPath($RegistryRoot)
  if(-not(Test-Path $config)){if(-not$Apply){return [ordered]@{status='PLANNED';writes_performed=$false}};$parent=Split-Path -Parent $config;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};New-Item -ItemType Directory -Path $config|Out-Null}
  $registryParent=Split-Path -Parent $registry
  if($Apply-and-not(Test-Path $registryParent -PathType Container)){New-Item -ItemType Directory -Path $registryParent -Force|Out-Null}
  $r=Initialize-SpectraProjectRegistry -RegistryRoot $registry -ObservedAt $ObservedAt -Apply:$Apply
  [ordered]@{status=$r.status;writes_performed=$r.writes_performed;config_root_ready=(Test-Path $config -PathType Container);registry_root_ready=(Test-Path $registry -PathType Container)}
}
function Invoke-SpectraDoctor([string]$ProductRoot,[string]$RegistryRoot,[string]$ConfigRoot,[string]$Version){
  $product=[IO.Path]::GetFullPath($ProductRoot);$registry=[IO.Path]::GetFullPath($RegistryRoot);$config=[IO.Path]::GetFullPath($ConfigRoot);if(-not(Test-Path $product)){throw 'BOOTSTRAP_PRODUCT_ROOT_MISSING'};if(-not(Test-Path $registry -PathType Container)){throw 'BOOTSTRAP_REGISTRY_ROOT_MISSING'};if(-not(Test-Path $config -PathType Container)){throw 'BOOTSTRAP_CONFIG_ROOT_MISSING'}
  Assert-SpectraToolAvailable git|Out-Null;Assert-SpectraToolAvailable node|Out-Null;$platform=Get-SpectraPlatform
  if($platform-eq'macos'){Assert-SpectraToolAvailable pwsh 'BOOTSTRAP_PWSH_MISSING'|Out-Null;if($PSVersionTable.PSEdition-ne'Core'-or$PSVersionTable.PSVersion.Major-lt7){throw 'BOOTSTRAP_PWSH7_REQUIRED'}}
  Assert-SpectraNoLinkPath $registry $registry;Assert-SpectraNoLinkPath $config $config;if((Test-SpectraPathPrefix -Root $registry -Path $product)-or(Test-SpectraPathPrefix -Root $config -Path $product)-or(Test-SpectraPathPrefix -Root $product -Path $registry)-or(Test-SpectraPathPrefix -Root $product -Path $config)){throw 'BOOTSTRAP_ROOT_OVERLAP'};if(-not(Test-SpectraRootWritableMetadata $registry)-or-not(Test-SpectraRootWritableMetadata $config)){throw 'BOOTSTRAP_ROOT_NOT_WRITABLE'};$installedMarker=Join-Path $product '.spectra-install.json';if(-not(Test-Path $installedMarker -PathType Leaf)){$gitRoot=(& git -C $product rev-parse --show-toplevel 2>$null);if($LASTEXITCODE-ne0-or[IO.Path]::GetFullPath($gitRoot)-ne$product){throw 'BOOTSTRAP_PRODUCT_GIT_INVALID'}};$binding=Get-SpectraReleaseBinding $product $Version
  [ordered]@{product_id='spectra';status='PASS';platform=$platform;powershell_runtime=if($platform-eq'macos'){'pwsh'}else{'powershell-or-pwsh'};powershell_version=$PSVersionTable.PSVersion.ToString();git_available=$true;node_available=$true;release_binding=$binding;registry_writable=Test-SpectraRootWritableMetadata $registry;config_writable=Test-SpectraRootWritableMetadata $config;homebrew_hints=@('brew install git','brew install node','brew install --cask powershell');windows_gate=if($platform-eq'windows'){'PASS'}else{'NOT_RUN'};macos_gate=if($platform-eq'macos'){'DOCTOR_PASS_TEST_EVIDENCE_REQUIRED'}else{'MACOS_RUNNER_EVIDENCE_MISSING'};writes_performed=$false}
}
function Test-SpectraRegisteredWorkspace([string]$RegistryRoot,[string]$ProductRoot,$Entry){
  $root=[IO.Path]::GetFullPath($RegistryRoot);Assert-SpectraNoLinkPath $root $root;$workspace=Join-Path $root (([string]$Entry.relative_path)-replace'/',[IO.Path]::DirectorySeparatorChar);Assert-SpectraNoLinkPath $root $workspace;if(-not(Test-Path $workspace -PathType Container)){throw 'BOOTSTRAP_WORKSPACE_MISSING'}
  & (Join-Path $ProductRoot 'automation\Test-CustomerWorkspace.ps1') -Path $workspace -ProductRoot $ProductRoot|Out-Null
  $ws=Read-SpectraBootstrapJson (Join-Path $workspace 'workspace.yaml');$profile=Read-SpectraBootstrapJson (Join-Path $workspace 'governance\policies\workspace-profile.yaml');$binding=Read-SpectraBootstrapJson (Join-Path $workspace 'governance\policies\release-binding.json')
  if([string]$ws.customer_id-cne[string]$Entry.customer_id-or[string]$profile.profile-cne[string]$Entry.profile){throw 'BOOTSTRAP_WORKSPACE_IDENTITY_MISMATCH'}
  if([string]$binding.release_version-cne[string]$Entry.release_version-or[string]$binding.tag_commit-cne[string]$Entry.release_commit-or[string]$binding.payload_bundle_digest-cne[string]$Entry.release_digest){throw 'BOOTSTRAP_WORKSPACE_RELEASE_MISMATCH'}
  if([string]$Entry.profile-eq'implementation'-and[string]::IsNullOrWhiteSpace([string]$Entry.project_id)){throw 'BOOTSTRAP_PROJECT_ID_REQUIRED'};$true
}
function Test-SpectraProjectRegistry($Registry,[string]$RegistryRoot,[string]$ProductRoot){
  Test-SpectraBootstrapSchema $Registry 'spectra-project-registry.schema.json';$ids=@{};$paths=@{};foreach($e in @($Registry.entries)){if($ids.ContainsKey([string]$e.workspace_id)){throw 'BOOTSTRAP_REGISTRY_DUPLICATE_ID'};$ids[[string]$e.workspace_id]=$true;if($paths.ContainsKey([string]$e.relative_path)){throw 'BOOTSTRAP_REGISTRY_DUPLICATE_PATH'};$paths[[string]$e.relative_path]=$true;if($RegistryRoot-and$ProductRoot){Test-SpectraRegisteredWorkspace -RegistryRoot $RegistryRoot -ProductRoot $ProductRoot -Entry $e|Out-Null}};$true
}
function Register-SpectraProject([string]$RegistryRoot,[string]$Workspace,[string]$WorkspaceId,[string]$ProjectId,[string]$Profile,[string]$Mode,$Binding,[string]$ObservedAt,[string]$ProductRoot){
  $root=[IO.Path]::GetFullPath($RegistryRoot);$workspacePath=[IO.Path]::GetFullPath($Workspace);Assert-SpectraNoLinkPath $root $workspacePath;$relative=ConvertTo-SpectraRelativePath $root $workspacePath;$path=Join-Path $root 'spectra-projects.json'
  if(Test-Path $path){$registry=Read-SpectraBootstrapJson $path}else{$registry=[ordered]@{schema_version=1;product_id='spectra';registry_id='REG-LOCAL-SPECTRA';created_at=$ObservedAt;entries=@()}}
  $existing=@($registry.entries|Where-Object workspace_id -ceq $WorkspaceId);if($existing.Count){$e=$existing[0];if($e.relative_path -ceq $relative -and $e.release_commit -ceq $Binding.commit -and [string]$e.project_id -ceq [string]$ProjectId -and [string]$e.profile -ceq [string]$Profile){Test-SpectraRegisteredWorkspace -RegistryRoot $root -ProductRoot $ProductRoot -Entry $e|Out-Null;return [ordered]@{status='ALREADY_REGISTERED';writes_performed=$false;relative_path=$relative}};throw 'BOOTSTRAP_REGISTRY_CONFLICT'}
  $ws=Read-SpectraBootstrapJson (Join-Path $workspacePath 'workspace.yaml');$entry=[ordered]@{workspace_id=$WorkspaceId;customer_id=[string]$ws.customer_id;project_id=if($ProjectId){$ProjectId}else{$null};profile=$Profile;mode=$Mode;relative_path=$relative;release_version=$Binding.version;release_tag=$Binding.tag;release_commit=$Binding.commit;release_tree=$Binding.tree;release_digest=$Binding.digest;registered_at=$ObservedAt;status='active'};$registry.entries=@($registry.entries)+@($entry);$registry.entries=@($registry.entries|Sort-Object workspace_id);Test-SpectraProjectRegistry $registry $root $ProductRoot|Out-Null;Write-SpectraBootstrapJson $path $registry;[ordered]@{status='REGISTERED';writes_performed=$true;relative_path=$relative}
}
function New-SpectraTwinHandoff([string]$Workspace,[string]$WorkspaceId,[string]$ProjectId,[string]$SnapshotPath,$Binding,[string]$ObservedAt){
  $root=[IO.Path]::GetFullPath($Workspace);$snapshot=[IO.Path]::GetFullPath($SnapshotPath);Assert-SpectraNoLinkPath $root $snapshot;if(-not(Test-Path $snapshot -PathType Leaf)){throw 'BOOTSTRAP_SNAPSHOT_MISSING'};. (Join-Path $PSScriptRoot 'PortableSnapshot.Catalog.ps1');$snapshotObject=Read-PortableJson $snapshot;Test-PortableSnapshotObject $snapshotObject|Out-Null;$workspaceObject=Read-SpectraBootstrapJson (Join-Path $root 'workspace.yaml');if([string]$workspaceObject.customer_id-cne[string]$snapshotObject.customer_id-or[string]$ProjectId-cne[string]$snapshotObject.project_id){throw 'BOOTSTRAP_SNAPSHOT_SCOPE_MISMATCH'}
  $releaseId='SRL-'+(([string]$snapshotObject.snapshot_id)-replace'^SNP-','');$releaseRelative="snapshots/releases/$releaseId/release.json";$releaseDir=Join-Path $root "snapshots\releases\$releaseId";$digest=Get-SpectraBootstrapSha $snapshot
  if(-not(Test-Path $releaseDir)){ $stage=Join-Path $root ('snapshots\.stage-'+[guid]::NewGuid().ToString('N'));try{New-Item -ItemType Directory -Path $stage -Force|Out-Null;Copy-Item -LiteralPath $snapshot -Destination (Join-Path $stage 'snapshot.json');$content=[Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $stage 'snapshot.json')));$release=[ordered]@{schema_version=1;product_id='spectra';release_id=$releaseId;snapshot_id=[string]$snapshotObject.snapshot_id;customer_id=[string]$snapshotObject.customer_id;project_id=[string]$snapshotObject.project_id;state='approved';immutable=$true;snapshot_path='snapshot.json';snapshot_sha256=$digest;transports=[ordered]@{contract_id='spectra-portable-project-snapshot-v1';media_type='application/vnd.spectra.project-snapshot+json';filesystem=[ordered]@{location='snapshot.json';payload_sha256=$digest};http=[ordered]@{location="/v1/customers/$($snapshotObject.customer_id)/projects/$ProjectId/snapshots/$($snapshotObject.snapshot_id)";payload_sha256=$digest;content_base64=$content}}};Test-PortableSchema $release 'portable-snapshot-release.schema.json';Write-PortableJson (Join-Path $stage 'release.json') $release;New-Item -ItemType Directory -Path (Split-Path -Parent $releaseDir) -Force|Out-Null;Move-Item -LiteralPath $stage -Destination $releaseDir}finally{if(Test-Path $stage){Remove-Item -LiteralPath $stage -Recurse -Force}} }
  $releasedSnapshot=Join-Path $releaseDir 'snapshot.json';if((Get-SpectraBootstrapSha $releasedSnapshot)-cne$digest){throw 'BOOTSTRAP_SNAPSHOT_IMMUTABILITY_CONFLICT'};$relative="snapshots/releases/$releaseId/snapshot.json";$handoff=[ordered]@{schema_version=1;product_id='spectra';workspace_id=$WorkspaceId;customer_id=[string]$snapshotObject.customer_id;project_id=$ProjectId;snapshot_id=[string]$snapshotObject.snapshot_id;release_manifest_path=$releaseRelative;snapshot_path=$relative;snapshot_sha256=$digest;release_version=$Binding.version;release_commit=$Binding.commit;created_at=$ObservedAt;read_only=$true};Test-SpectraBootstrapSchema $handoff 'spectra-twin-handoff.schema.json';$path=Join-Path $root 'twin-handoff.json';if(Test-Path $path){$old=Read-SpectraBootstrapJson $path;if(($old|ConvertTo-Json -Depth 20 -Compress)-ceq($handoff|ConvertTo-Json -Depth 20 -Compress)){return [ordered]@{status='ALREADY_CURRENT';writes_performed=$false;path=$path}};throw 'BOOTSTRAP_HANDOFF_CONFLICT'};Write-SpectraBootstrapJson $path $handoff;Write-SpectraBootstrapJson (Join-Path $root 'snapshots\current.json') ([ordered]@{release_id=$releaseId;release_manifest_path=$releaseRelative;snapshot_sha256=$digest});[ordered]@{status='CREATED';writes_performed=$true;path=$path}
}
function Test-SpectraTwinHandoff([string]$Workspace){$root=[IO.Path]::GetFullPath($Workspace);$h=Read-SpectraBootstrapJson (Join-Path $root 'twin-handoff.json');Test-SpectraBootstrapSchema $h 'spectra-twin-handoff.schema.json';$snapshot=Join-Path $root ($h.snapshot_path-replace'/',[IO.Path]::DirectorySeparatorChar);$release=Join-Path $root ($h.release_manifest_path-replace'/',[IO.Path]::DirectorySeparatorChar);if((Get-SpectraBootstrapSha $snapshot)-cne[string]$h.snapshot_sha256){throw 'BOOTSTRAP_SNAPSHOT_DIGEST_MISMATCH'};. (Join-Path $PSScriptRoot 'PortableSnapshot.Catalog.ps1');$r=Read-PortableJson $release;Test-PortableSchema $r 'portable-snapshot-release.schema.json';$s=Read-PortableJson $snapshot;Test-PortableSnapshotObject $s|Out-Null;if([string]$r.snapshot_sha256-cne[string]$h.snapshot_sha256-or[string]$r.customer_id-cne[string]$h.customer_id-or[string]$r.project_id-cne[string]$h.project_id){throw 'BOOTSTRAP_HANDOFF_RELEASE_MISMATCH'};$http=[Convert]::FromBase64String([string]$r.transports.http.content_base64);$bytes=[IO.File]::ReadAllBytes($snapshot);if($http.Length-ne$bytes.Length){throw 'BOOTSTRAP_HANDOFF_TRANSPORT_MISMATCH'};$true}
