[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';$d=[IO.Path]::GetFullPath($Path);$x=Get-Content (Join-Path $d 'project-story.json') -Raw|ConvertFrom-Json
$schema=Get-Content (Join-Path $PSScriptRoot '..\schemas\project-story.schema.json') -Raw|ConvertFrom-Json
foreach($name in @($schema.required)){if($null -eq $x.PSObject.Properties[$name]){throw 'STORY_SCHEMA_REQUIRED'}}
if($null -eq $x.offer -or $null -eq $x.pages -or $null -eq $x.tickets -or $null -eq $x.timeline -or $null -eq $x.hypercare -or $null -eq $x.evidence -or $null -eq $x.graph){throw 'STORY_SCHEMA_REQUIRED'}
$ids=@($x.offer.id)+@($x.pages|% id)+@($x.tickets|% id)+@($x.evidence|% id)+@($x.timeline|% id)
if(($ids|Sort-Object -Unique).Count -ne $ids.Count){throw 'STORY_DUPLICATE_ID'}
$pageIds=@($x.pages|% id);$paths=@()
foreach($p in @($x.pages)){if([string]::IsNullOrWhiteSpace($p.sourcePath)-or $p.sourcePath -match '(^[A-Za-z]:|^/|\.\.|\\)'){throw 'STORY_PAGE_SOURCE_INVALID'};if($paths -contains $p.sourcePath){throw 'STORY_PAGE_SOURCE_DUPLICATE'};$paths+=$p.sourcePath;$f=Join-Path $d $p.sourcePath;if(-not(Test-Path $f -PathType Leaf)){throw 'STORY_PAGE_SOURCE_INVALID'};if((Get-Content $f -Raw).Trim().Length -eq 0){throw 'STORY_PAGE_EMPTY'};if($p.parent -and $pageIds -notcontains $p.parent){throw 'STORY_PAGE_PARENT_INVALID'}}
function Test-PageCycles($pages){foreach($p in @($pages)){ $seen=@{};$cur=$p;while($cur.parent){if($seen.ContainsKey($cur.id)){throw 'STORY_PAGE_CYCLE'};$seen[$cur.id]=$true;$cur=@($pages|? id -eq $cur.parent)|Select-Object -First 1;if($null -eq $cur){break}}}}
Test-PageCycles $x.pages
$hours=0;$cost=0
foreach($t in @($x.tickets)){if([string]::IsNullOrWhiteSpace($t.reporter)-or [string]::IsNullOrWhiteSpace($t.assignee)-or $t.priority -notin @('P1','P2','P3','P4')-or @($t.acceptance).Count -eq 0){throw 'STORY_TICKET_FIELDS_INVALID'};if($t.parent -and $t.parent -ne 'TKT-HARD-EPIC' -and $ids -notcontains $t.parent){throw 'STORY_TICKET_PARENT_INVALID'};$hist=@($t.status_history);for($i=1;$i -lt $hist.Count;$i++){if([datetime]$hist[$i].time -lt [datetime]$hist[$i-1].time){throw 'STORY_STATUS_TIME_TRAVEL'}};if($hist.Count -eq 0 -or $hist[-1].status -ne $t.status_history[-1].status){throw 'STORY_STATUS_TERMINAL_MISMATCH'};if($hist[-1].status -in @('done','closed') -and @($t.comments|? type -eq 'closing').Count -ne 1){throw 'STORY_CLOSING_COMMENT_MISSING'};if(@($t.comments|? type -eq 'working').Count -lt 1){throw 'STORY_WORKING_COMMENT_MISSING'};foreach($c in @($t.comments)){if([string]::IsNullOrWhiteSpace($c.id)-or [string]::IsNullOrWhiteSpace($c.author_role)-or $c.type -notin @('working','handoff','closing')){throw 'STORY_COMMENT_INVALID'}};foreach($w in @($t.worklogs)){if($w.hours -le 0){throw 'STORY_WORKLOG_INVALID'};$hours+=$w.hours;$cost+=$w.cost}}
if($hours -ne $x.offer.actual_hours -or $cost -ne $x.offer.actual_cost){throw 'STORY_WORKLOG_TOTAL_INVALID'}
$valid=@($ids);foreach($e in @($x.timeline)){foreach($r in @($e.references)){if($valid -notcontains $r){throw 'STORY_TIMELINE_REFERENCE_INVALID'}};if([string]::IsNullOrWhiteSpace($e.role)-or [string]::IsNullOrWhiteSpace($e.action)-or [string]::IsNullOrWhiteSpace($e.result)-or [string]::IsNullOrWhiteSpace($e.nextStep)-or @($e.evidence).Count -eq 0){throw 'STORY_TIMELINE_FIELDS_INVALID'}};for($i=1;$i -lt @($x.timeline).Count;$i++){if([datetime]$x.timeline[$i].time -lt [datetime]$x.timeline[$i-1].time){throw 'STORY_TIMELINE_ORDER_INVALID'}}
foreach($h in @($x.hypercare)){if([string]::IsNullOrWhiteSpace($h.daily_page)-or $valid -notcontains $h.daily_page-or @($h.tickets).Count -eq 0-or [string]::IsNullOrWhiteSpace($h.diagnosis)-or [string]::IsNullOrWhiteSpace($h.fix)-or [string]::IsNullOrWhiteSpace($h.retest)-or $h.go_no_go -notin @('GO','NO-GO')){throw 'STORY_HYPERCARE_FIELDS_INVALID'}};if(@($x.hypercare|? status -ne 'closed').Count -gt 0){throw 'STORY_HYPERCARE_INCOMPLETE'}
$seenEdges=@{};foreach($e in @($x.graph)){if($valid -notcontains $e.from-or $valid -notcontains $e.to){throw 'STORY_GRAPH_REFERENCE_INVALID'};$k="$($e.from)|$($e.to)|$($e.type)";if($seenEdges.ContainsKey($k)){throw 'STORY_GRAPH_DUPLICATE'};$seenEdges[$k]=$true};foreach($e in @($x.graph)){if(-not(@($x.graph|? { $_.from -eq $e.to -and $_.to -eq $e.from}).Count)){throw 'STORY_GRAPH_INVERSE_MISSING'}}
Write-Host 'PASS: Project-story schema, history, pages, timeline, hypercare and graph validated.'
