[CmdletBinding()]param()
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0;$root=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$version='0.1.0-alpha.1';$sandbox=Join-Path ([System.IO.Path]::GetTempPath()) ('spectra-promotion-'+[Guid]::NewGuid().ToString('N'))
function Invoke-Quiet([string]$File,[string[]]$Arguments){& $File @Arguments 2>&1|Out-Null;return $LASTEXITCODE}
try{
 [void](New-Item -ItemType Directory -Path $sandbox);$repo=Join-Path $sandbox 'repo';[void](New-Item -ItemType Directory -Path $repo);foreach($rel in @('AGENTS.md','README.md','automation','catalogs','contract','examples\minimal-contract','schemas','tests\invalid','release')){$src=Join-Path $root $rel;$dst=Join-Path $repo $rel;$dir=Split-Path -Parent $dst;if(-not(Test-Path $dir)){[void](New-Item -ItemType Directory -Path $dir -Force)};Copy-Item $src $dst -Recurse -Force};& git -C $repo init -b main|Out-Null;& git -C $repo config core.autocrlf false;& git -C $repo config user.email 'spectra-promotion@example.invalid';& git -C $repo config user.name 'Spectra Promotion';& git -C $repo remote add origin 'https://github.com/sivla/BCProjectOS.git';& git -C $repo add -A;& git -C $repo commit -m source|Out-Null
 $candidateWorkspace=Join-Path $sandbox 'candidate-workspace';& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'automation\New-CustomerWorkspace.ps1') -Destination $candidateWorkspace -Profile implementation -CustomerAlias alpha-fixture -ExpectedBlueprintVersion $version -ProductRoot $repo;if($LASTEXITCODE-eq 0){throw 'UNBOUND_CANDIDATE_INSTALL_ACCEPTED'};Write-Host 'PASS: Unbound candidate installation is blocked.'
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\New-ReleaseCandidate.ps1') -Version $version -ReleaseDate 2026-07-11 | Out-Null; & git -C $repo add release/versions/$version; & git -C $repo commit -m candidate | Out-Null
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Promote-ReleaseCandidate.ps1') -RepositoryRoot $repo -Version $version -SyntheticRepository; if($LASTEXITCODE-ne 0){throw 'PROMOTION_FAILED'}
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Test-ReleaseCandidate.ps1') -Version $version -RequirePublished; if($LASTEXITCODE-ne 0){throw 'FINAL_VALIDATION_FAILED'};Write-Host 'PASS: Candidate-to-final promotion and release validation.'
 $workspace=Join-Path $sandbox 'workspace';& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'automation\New-CustomerWorkspace.ps1') -Destination $workspace -Profile implementation -CustomerAlias alpha-fixture -ExpectedBlueprintVersion $version -ProductRoot $repo; if($LASTEXITCODE-ne 0){throw 'INSTALLATION_FAILED'};Write-Host 'PASS: Final promoted release installs.'
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Promote-ReleaseCandidate.ps1') -RepositoryRoot $repo -Version $version -SyntheticRepository;if($LASTEXITCODE-eq 0){throw 'EXISTING_VERSION_ACCEPTED'};Write-Host 'PASS: Existing final version/tag is blocked.'
}
finally{if(Test-Path $sandbox){Remove-Item $sandbox -Recurse -Force}}
