[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path,[Parameter(Mandatory=$true)][string]$ProductRoot)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
function Fail([string]$Code){throw "WORKSPACE_VALIDATION_FAILED:$Code"}
$root=[IO.Path]::GetFullPath($Path);$product=[IO.Path]::GetFullPath($ProductRoot);if(-not(Test-Path $root -PathType Container)){Fail 'ROOT_MISSING'}
$workspaceFile=Join-Path $root 'workspace.yaml';$profileFile=Join-Path $root 'governance\policies\workspace-profile.yaml';$bindingFile=Join-Path $root 'governance\policies\release-binding.json';foreach($f in @($workspaceFile,$profileFile,$bindingFile)){if(-not(Test-Path $f -PathType Leaf)){Fail "REQUIRED_FILE_MISSING:$f"}}
$ws=Get-Content $workspaceFile -Raw|ConvertFrom-Json;$schema=Get-Content (Join-Path $product 'schemas\workspace.schema.json') -Raw|ConvertFrom-Json
if([int]$ws.schema_version -ne 1 -or [string]$ws.id -notmatch '^CUS-[0-9A-HJKMNP-TV-Z]{26}$' -or [string]$ws.customer_id -ne [string]$ws.id -or [string]$ws.entity_type -ne 'customer' -or @($ws.relations).Count -ne 0 -or @($ws.openspec_roots).Count -ne 1 -or [string]$ws.openspec_roots[0] -ne 'openspec' -or [string]$ws.blueprint_id -ne 'bcprojectos'){Fail 'WORKSPACE_SCHEMA_OR_ID_INVALID'}
if([string]$ws.blueprint_version -notmatch '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' -or [string]$ws.created_with_version -ne [string]$ws.blueprint_version){Fail 'VERSION_INVALID'}
$profile=Get-Content $profileFile -Raw|ConvertFrom-Json;if([string]$profile.profile -notin @('implementation','support-only','mixed')){Fail 'PROFILE_INVALID'}
$binding=Get-Content $bindingFile -Raw|ConvertFrom-Json;if([string]$binding.binding_status -ne 'BOUND' -or [string]$binding.product_id -ne 'spectra' -or [string]$binding.consumer_mode -ne 'INSTALLABLE_BLUEPRINT' -or $binding.installable_blueprint -ne $true -or [string]$binding.release_version -ne [string]$ws.blueprint_version){Fail 'RELEASE_BINDING_INVALID'}
. (Join-Path $PSScriptRoot 'Release.Common.ps1');$manifestPath=Join-Path $product ([string]$binding.manifest_path -replace '/','\');if(-not(Test-Path $manifestPath -PathType Leaf)){Fail 'MANIFEST_MISSING'};$manifest=Get-Content $manifestPath -Raw|ConvertFrom-Json;if([string]$manifest.manifest_state -ne 'final' -or [string]$manifest.source_commit -ne [string]$binding.manifest_source_commit){Fail 'MANIFEST_BINDING_INVALID'}
$scope=Get-BCProjectOSReleaseScope -Root $product;$records=@(Get-BCProjectOSGitPayloadRecords -Root $product -Revision ([string]$manifest.source_commit) -Scope $scope);$digest=Get-BCProjectOSTextSha256 (Get-BCProjectOSChecksumsText $records);if($digest -ne [string]$binding.payload_bundle_digest -or $digest -ne [string]$manifest.payload.bundle_digest){Fail 'PAYLOAD_DIGEST_INVALID'}
$expectedCatalogs=@(Get-ChildItem (Join-Path $product 'catalogs') -File|% Name|Sort-Object);$actualCatalogs=@(Get-ChildItem (Join-Path $root 'governance\catalogs') -File|% Name|Sort-Object);if((Compare-Object $expectedCatalogs $actualCatalogs)){Fail 'CATALOG_SET_INVALID'};foreach($name in $expectedCatalogs){if((Get-FileHash (Join-Path $product "catalogs\$name")).Hash -ne (Get-FileHash (Join-Path $root "governance\catalogs\$name")).Hash){Fail "CATALOG_DRIFT:$name"}}
$openSpecRoots=@(Get-ChildItem $root -Directory -Recurse -Filter openspec);if($openSpecRoots.Count -ne 1){Fail 'OPENSPEC_ROOT_COUNT_INVALID'};foreach($dir in @('projects','support','meetings','work','evidence','generated','external-files\inbox')){if(-not(Test-Path (Join-Path $root $dir) -PathType Container)){Fail "REQUIRED_PATH_MISSING:$dir"}}
$entityDirs=@('projects','support','meetings','work','evidence','knowledge');foreach($dir in $entityDirs){foreach($file in @(Get-ChildItem (Join-Path $root $dir) -File -Recurse -Filter *.json -ErrorAction SilentlyContinue)){try{$entity=Get-Content $file.FullName -Raw|ConvertFrom-Json}catch{Fail "ENTITY_JSON_INVALID:$($file.FullName)"};if([int]$entity.schema_version -ne 1 -or [string]$entity.id -notmatch '^(CUS|PRJ|SUP|MTG|FILE|KNO|PROC|BR|TKT|REQ|CHG|EVD)-[0-9A-Z]{26}$' -or [string]$entity.customer_id -ne [string]$ws.customer_id -or [string]$entity.entity_type -notin @('customer','project','support_case','meeting','external_file','knowledge_item','business_process','business_rule','ticket','requirement','openspec_change','evidence') -or [string]$entity.lifecycle_status -notin @('draft','active','inactive','archived','deleted') -or $null -eq $entity.relations){Fail "ENTITY_CONTRACT_INVALID:$($file.FullName)"};foreach($relation in @($entity.relations)){if([string]$relation.target_id -notmatch '^(CUS|PRJ|SUP|MTG|FILE|KNO|PROC|BR|TKT|REQ|CHG|EVD)-[0-9A-Z]{26}$'){Fail "RELATION_TARGET_INVALID:$($file.FullName)"}};if([string]$entity.entity_type -eq 'evidence' -and [string]$entity.evidence_type -notin @('approval','automated_test','uat','documentation','training','release','integrity','meeting_confirmation')){Fail "EVIDENCE_TYPE_INVALID:$($file.FullName)"}}}
$specialDirs=@('evidence','external-files\register','external-files\derived','work');foreach($dir in $specialDirs){foreach($file in @(Get-ChildItem (Join-Path $root $dir) -File -Recurse -Filter *.json -ErrorAction SilentlyContinue)){ $item=Get-Content $file.FullName -Raw|ConvertFrom-Json;if([string]$item.entity_type -eq 'evidence'){if([string]$item.evidence_type -notin @('approval','automated_test','uat','documentation','training','release','integrity','meeting_confirmation')){Fail 'EVIDENCE_TYPE_INVALID'};if([string]$item.evidence_type -in @('uat','automated_test','release') -and $null -eq $item.evidence_refs){Fail 'EVIDENCE_REFS_REQUIRED'}};if([string]$item.entity_type -eq 'external_file'){if([string]$item.sha256 -notmatch '^[a-f0-9]{64}$' -or [int]$item.size_bytes -lt 0 -or [string]$item.blob_path -notmatch '^external-files/originals/sha256/[a-f0-9]{2}/[a-f0-9]{64}$'){Fail 'EXTERNAL_FILE_CONTRACT_INVALID'};if(([string]$item.blob_path -split '/')[3] -ne ([string]$item.sha256).Substring(0,2)){Fail 'EXTERNAL_BLOB_PATH_HASH_PREFIX_INVALID'};$blob=Join-Path $root ([string]$item.blob_path -replace '/','\');if(-not(Test-Path $blob -PathType Leaf)){Fail 'EXTERNAL_BLOB_MISSING'};if((Get-FileHash $blob -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$item.sha256){Fail 'EXTERNAL_BLOB_HASH_MISMATCH'}}}}
$scan=@(Get-ChildItem $root -File -Recurse|Where-Object{$_.FullName -notmatch '\\external-files\\originals(\\|$)'});foreach($file in $scan){$text=Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue;if($text -match '(?i)(password|client[_-]?secret|access[_-]?token|tenant[_-]?id)'){Fail "SENSITIVE_PATTERN:$($file.FullName)"}}
Write-Host 'PASS: Spectra customer workspace is schema-, release-, catalog- and boundary-valid (read-only).'
