[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0;$file=Join-Path ([IO.Path]::GetFullPath($Path)) 'uat-training-defects.json';if(-not(Test-Path $file -PathType Leaf)){throw 'UAT_RECORD_MISSING'};$before=(Get-FileHash $file -Algorithm SHA256).Hash;$x=Get-Content $file -Raw|ConvertFrom-Json
. (Join-Path $PSScriptRoot 'Spectra.JsonSchema.ps1');$s=Get-Content (Join-Path $PSScriptRoot '..\schemas\uat-training-defects.schema.json') -Raw|ConvertFrom-Json;try{Test-SpectraJsonSchema -Value $x -Schema $s -RootSchema $s -Path root}catch{throw 'UAT_TRAINING_DEFECT_SCHEMA_INVALID'}
$all=@();$all+=@($x.roles.id);$all+=@($x.test_cases.id);$all+=@($x.training_paths.id);$all+=@($x.defects.id);$all+=@($x.evidence.id);$all+=@($x.decisions.id);$all+=$x.uat_plan.id;if(@($all|Sort-Object -Unique).Count-ne$all.Count){throw 'UAT_DUPLICATE_ID'}
$roles=@($x.roles.id);$ev=@($x.evidence.id);$dec=@($x.decisions.id);$tests=@($x.test_cases.id);$required=@('finance','p2p','o2c','cash_bank','inventory','month_end','vat_preview');if(Compare-Object $required @($x.uat_plan.required_processes|Sort-Object -Unique)){throw 'UAT_CORE_PROCESS_COVERAGE_MISSING'};if(@($x.uat_plan.entry_criteria).Count-eq0-or@($x.uat_plan.exit_criteria).Count-eq0){throw 'UAT_ENTRY_EXIT_CRITERIA_MISSING'}
if($x.uat_plan.owner_role-notin$roles-or@($x.uat_plan.evidence_refs|Where-Object{$_-notin$ev}).Count){throw 'UAT_REFERENCE_UNKNOWN'};$paths=@($x.test_cases.path_type|Sort-Object -Unique);foreach($p in @('positive','negative','exception','retest')){if($p-notin$paths){throw 'UAT_PATH_COVERAGE_MISSING'}}
foreach($t in $x.test_cases){if($t.role_ref-notin$roles-or$t.owner_role-notin$roles-or@($t.evidence_refs|Where-Object{$_-notin$ev}).Count-or@($t.decision_refs|Where-Object{$_-notin$dec}).Count){throw 'UAT_REFERENCE_UNKNOWN'};if(@($t.evidence_refs).Count-eq0){throw 'UAT_RESULT_EVIDENCE_MISSING'}}
foreach($t in $x.training_paths){if($t.role_ref-notin$roles){throw 'TRAINING_ROLE_UNKNOWN'};if($t.competency_evidence_ref-notin$ev){throw 'TRAINING_COMPETENCY_EVIDENCE_MISSING'};if([string]::IsNullOrWhiteSpace([string]$t.operator_smoke)){throw 'TRAINING_OPERATOR_SMOKE_MISSING'}}
$allowed=@{new=@('triaged');triaged=@('in_progress','fixed','waived');in_progress=@('fixed');fixed=@('retest');retest=@('closed')};foreach($d in $x.defects){if($d.test_ref-notin$tests-or$d.owner_role-notin$roles){throw 'UAT_REFERENCE_UNKNOWN'};if(@($d.reproduction_steps).Count-eq0){throw 'DEFECT_REPRODUCTION_MISSING'};$h=@($d.status_history);for($i=1;$i-lt$h.Count;$i++){if([datetime]$h[$i].time-le[datetime]$h[$i-1].time-or$h[$i].status-notin@($allowed[[string]$h[$i-1].status])){throw 'DEFECT_STATUS_TRANSITION_INVALID'}};if($h[-1].status-ne$d.status){throw 'DEFECT_STATUS_TRANSITION_INVALID'};if($d.status-in@('fixed','retest','closed')-and(@($d.fix_evidence_refs).Count-eq0-or@($d.retest_evidence_refs).Count-eq0-or@($d.fix_evidence_refs|Where-Object{$_-notin$ev}).Count-or@($d.retest_evidence_refs|Where-Object{$_-notin$ev}).Count)){throw 'DEFECT_FIX_RETEST_EVIDENCE_MISSING'};if($d.status-eq'waived'-and([string]::IsNullOrWhiteSpace([string]$d.waiver_decision_ref)-or$d.waiver_decision_ref-notin$dec)){throw 'DEFECT_WAIVER_DECISION_MISSING'}}
$openP1=@($x.defects|Where-Object{$_.priority-eq'P1'-and$_.status-notin@('closed','waived')}).Count;$openP2=@($x.defects|Where-Object{$_.priority-eq'P2'-and$_.status-notin@('closed','waived')}).Count;if($openP1-ne[int]$x.exit_gate.open_p1-or$openP2-ne[int]$x.exit_gate.open_p2-or(($openP1+$openP2)-gt0-and$x.exit_gate.status-eq'GO')){throw 'UAT_EXIT_OPEN_HIGH_PRIORITY'};if($x.exit_gate.decision_ref-notin$dec){throw 'UAT_REFERENCE_UNKNOWN'}
$raw=Get-Content $file -Raw;if($raw-match'(?i)(credential_marker|tenant_marker|customer_content_marker)'){throw 'UAT_CUSTOMER_OR_SECRET_MARKER'};if((Get-FileHash $file -Algorithm SHA256).Hash-ne$before){throw 'UAT_VALIDATOR_MUTATED_SOURCE'};Write-Host 'PASS: UAT, Training, Defects, Evidence und Exit sind konsistent.'
