[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';$d=[IO.Path]::GetFullPath($Path);$x=Get-Content (Join-Path $d 'project-story.json') -Raw|ConvertFrom-Json
$schema=Get-Content (Join-Path $PSScriptRoot '..\schemas\project-story.schema.json') -Raw|ConvertFrom-Json
function Get-Prop($o,[string]$n){if($null -eq $o){return $null};$p=$o.PSObject.Properties[$n];if($null -eq $p){return $null};return $p.Value}
function Has-Prop($o,[string]$n){return ($null -ne $o -and $null -ne $o.PSObject.Properties[$n])}
function Resolve-Ref($r){$parts=$r.Substring(8);$defs=Get-Prop $schema '$defs';return Get-Prop $defs $parts}
function Test-SchemaNode($v,$n,[string]$p='root') {
  if($null -ne (Get-Prop $n '$ref')){$n=Resolve-Ref (Get-Prop $n '$ref')}
  $types=@(Get-Prop $n 'type');$ok=$false
  foreach($t in $types){$ok = $ok -or (($t -eq 'null' -and $null -eq $v) -or ($t -eq 'object' -and $null -ne $v -and $null -ne $v.PSObject.Properties) -or ($t -eq 'array' -and $v -is [System.Collections.IList] -and -not($v -is [string])) -or ($t -eq 'string' -and $v -is [string]) -or ($t -eq 'integer' -and $v -is [int]) -or ($t -eq 'number' -and $v -is [ValueType] -and $v -isnot [bool] -and $v -isnot [datetime]))}
  if(-not $ok){throw "STORY_SCHEMA_TYPE_INVALID:$p"}
  $enum=Get-Prop $n 'enum';if($null -ne $enum -and @($enum) -notcontains $v){throw "STORY_SCHEMA_ENUM_INVALID:$p"}
  $min=Get-Prop $n 'minLength';if($null -ne $min -and $v -is [string] -and $v.Length -lt $min){throw "STORY_SCHEMA_MIN_LENGTH:$p"}
  $pat=Get-Prop $n 'pattern';if($null -ne $pat -and $v -is [string] -and $v -notmatch $pat){throw "STORY_SCHEMA_PATTERN_INVALID:$p"}
  $mi=Get-Prop $n 'minimum';if($null -ne $mi -and $v -is [ValueType] -and $v -lt $mi){throw "STORY_SCHEMA_RANGE_INVALID:$p"}
  $ex=Get-Prop $n 'exclusiveMinimum';if($null -ne $ex -and $v -is [ValueType] -and $v -le $ex){throw "STORY_SCHEMA_RANGE_INVALID:$p"}
  if($v -is [string]){ $fmt=Get-Prop $n 'format';if($fmt -eq 'date-time' -or $fmt -eq 'date'){try{[datetime]::Parse($v)|Out-Null}catch{throw "STORY_SCHEMA_FORMAT_INVALID:$p"}};return }
  if($v -is [System.Collections.IList] -and -not($v -is [string])){$items=Get-Prop $n 'items';$i=0;foreach($z in $v){if($null -ne $items){Test-SchemaNode $z $items "$p[$i]"};$i++};return}
  if($v -is [pscustomobject]){$req=@(Get-Prop $n 'required');foreach($r in $req){if(-not(Has-Prop $v $r)){throw "STORY_SCHEMA_REQUIRED:$p.$r"}};$props=Get-Prop $n 'properties';$allow=Get-Prop $n 'additionalProperties';foreach($pr in $v.PSObject.Properties){$spec=if($null -ne $props){Get-Prop $props $pr.Name}else{$null};if($null -eq $spec -and $allow -eq $false){throw "STORY_SCHEMA_ADDITIONAL_PROPERTY:$p.$($pr.Name)"};if($null -ne $spec){Test-SchemaNode $pr.Value $spec "$p.$($pr.Name)"}}}
}
Test-SchemaNode $x $schema
foreach($name in @($schema.required)){if($null -eq $x.PSObject.Properties[$name]){throw 'STORY_SCHEMA_REQUIRED'}}
if($null -eq $x.offer -or $null -eq $x.pages -or $null -eq $x.tickets -or $null -eq $x.timeline -or $null -eq $x.hypercare -or $null -eq $x.evidence -or $null -eq $x.graph){throw 'STORY_SCHEMA_REQUIRED'}
$ids=@($x.offer.id)+@($x.pages|% id)+@($x.tickets|% id)+@($x.evidence|% id)+@($x.timeline|% id)
if(($ids|Sort-Object -Unique).Count -ne $ids.Count){throw 'STORY_DUPLICATE_ID'}
$pageIds=@($x.pages|% id);$paths=@()
foreach($p in @($x.pages)){if([string]::IsNullOrWhiteSpace($p.sourcePath)-or $p.sourcePath -match '(^[A-Za-z]:|^/|\.\.|\\)'){throw 'STORY_PAGE_SOURCE_INVALID'};if($paths -contains $p.sourcePath){throw 'STORY_PAGE_SOURCE_DUPLICATE'};$paths+=$p.sourcePath;$f=Join-Path $d $p.sourcePath;if(-not(Test-Path $f -PathType Leaf)){throw 'STORY_PAGE_SOURCE_INVALID'};if((Get-Content $f -Raw).Trim().Length -eq 0){throw 'STORY_PAGE_EMPTY'};if($p.parent -and $pageIds -notcontains $p.parent){throw 'STORY_PAGE_PARENT_INVALID'}}
function Test-PageCycles($pages){foreach($p in @($pages)){ $seen=@{};$cur=$p;while($cur.parent){if($seen.ContainsKey($cur.id)){throw 'STORY_PAGE_CYCLE'};$seen[$cur.id]=$true;$cur=@($pages|? id -eq $cur.parent)|Select-Object -First 1;if($null -eq $cur){break}}}}
Test-PageCycles $x.pages
$metaCheck=$true;foreach($p in @($x.pages)){ $txt=Get-Content (Join-Path $d $p.sourcePath) -Raw;if($txt -notmatch "id:\s*$($p.id)" -or $txt -notmatch "version:\s*$($p.version)" -or $txt -notmatch "status:\s*$($p.status)"){throw 'STORY_PAGE_METADATA_MISMATCH'} }
$hours=0;$cost=0
foreach($t in @($x.tickets)){if([string]::IsNullOrWhiteSpace($t.reporter)-or [string]::IsNullOrWhiteSpace($t.assignee)-or $t.priority -notin @('P1','P2','P3','P4')-or @($t.acceptance).Count -eq 0){throw 'STORY_TICKET_FIELDS_INVALID'};if($t.parent -and $t.parent -ne 'TKT-HARD-EPIC' -and $ids -notcontains $t.parent){throw 'STORY_TICKET_PARENT_INVALID'};$hist=@($t.status_history);for($i=1;$i -lt $hist.Count;$i++){if([datetime]$hist[$i].time -lt [datetime]$hist[$i-1].time){throw 'STORY_STATUS_TIME_TRAVEL'}};if($hist.Count -eq 0 -or $hist[-1].status -ne $t.status_history[-1].status){throw 'STORY_STATUS_TERMINAL_MISMATCH'};if($hist[-1].status -in @('done','closed') -and @($t.comments|? type -eq 'closing').Count -ne 1){throw 'STORY_CLOSING_COMMENT_MISSING'};if(@($t.comments|? type -eq 'working').Count -lt 1){throw 'STORY_WORKING_COMMENT_MISSING'};foreach($c in @($t.comments)){if([string]::IsNullOrWhiteSpace($c.id)-or [string]::IsNullOrWhiteSpace($c.author_role)-or $c.type -notin @('working','handoff','closing')){throw 'STORY_COMMENT_INVALID'}};foreach($w in @($t.worklogs)){if($w.hours -le 0){throw 'STORY_WORKLOG_INVALID'};$hours+=$w.hours;$cost+=$w.cost}}
if($hours -ne $x.offer.actual_hours -or $cost -ne $x.offer.actual_cost){throw 'STORY_WORKLOG_TOTAL_INVALID'}
$valid=@($ids);foreach($e in @($x.timeline)){foreach($r in @($e.references)){if($valid -notcontains $r){throw 'STORY_TIMELINE_REFERENCE_INVALID'}};if([string]::IsNullOrWhiteSpace($e.role)-or [string]::IsNullOrWhiteSpace($e.action)-or [string]::IsNullOrWhiteSpace($e.result)-or [string]::IsNullOrWhiteSpace($e.nextStep)-or @($e.evidence).Count -eq 0){throw 'STORY_TIMELINE_FIELDS_INVALID'}};for($i=1;$i -lt @($x.timeline).Count;$i++){if([datetime]$x.timeline[$i].time -lt [datetime]$x.timeline[$i-1].time){throw 'STORY_TIMELINE_ORDER_INVALID'}}
foreach($h in @($x.hypercare)){if([string]::IsNullOrWhiteSpace($h.daily_page)-or $valid -notcontains $h.daily_page-or @($h.tickets).Count -eq 0-or [string]::IsNullOrWhiteSpace($h.diagnosis)-or [string]::IsNullOrWhiteSpace($h.fix)-or [string]::IsNullOrWhiteSpace($h.retest)-or $h.go_no_go -notin @('GO','NO-GO')){throw 'STORY_HYPERCARE_FIELDS_INVALID'}};if(@($x.hypercare|? status -ne 'closed').Count -gt 0){throw 'STORY_HYPERCARE_INCOMPLETE'}
$seenEdges=@{};foreach($e in @($x.graph)){if($valid -notcontains $e.from-or $valid -notcontains $e.to){throw 'STORY_GRAPH_REFERENCE_INVALID'};$k="$($e.from)|$($e.to)|$($e.type)";if($seenEdges.ContainsKey($k)){throw 'STORY_GRAPH_DUPLICATE'};$seenEdges[$k]=$true};foreach($e in @($x.graph)){if(-not(@($x.graph|? { $_.from -eq $e.to -and $_.to -eq $e.from}).Count)){throw 'STORY_GRAPH_INVERSE_MISSING'}}
foreach($t in @($x.tickets)){if([string]::IsNullOrWhiteSpace([string]$t.status)){throw 'STORY_STATUS_TERMINAL_MISMATCH'};if(@($t.status_history)[0].status -ne 'open' -or @($t.status_history)[-1].status -ne $t.status){throw 'STORY_STATUS_TERMINAL_MISMATCH'}}
foreach($h in @($x.hypercare)){foreach($tid in @($h.tickets)){ $tt=@($x.tickets|? id -eq $tid)|Select-Object -First 1;if($tt.priority -in @('P1','P2') -and $tt.status -notin @('done','closed')){throw 'STORY_HYPERCARE_OPEN_HIGH_PRIORITY'}}}
$inverse=@{'offer-page'='page-offer';'page-offer'='offer-page';'page-ticket'='ticket-page';'ticket-page'='page-ticket';'ticket-evidence'='evidence-ticket';'evidence-ticket'='ticket-evidence'};foreach($e in @($x.graph)){if(-not $inverse.ContainsKey([string]$e.type)){throw 'STORY_GRAPH_RELATION_INVALID'};$back=@($x.graph|? {$_.from -eq $e.to -and $_.to -eq $e.from -and $_.type -eq $inverse[[string]$e.type]});if($back.Count -ne 1){throw 'STORY_GRAPH_INVERSE_TYPE_MISMATCH'}}
Write-Host 'PASS: Project-story schema, history, pages, timeline, hypercare and graph validated.'
