[CmdletBinding()]param([string]$Version='1.1.0-alpha.1')
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
. (Join-Path $PSScriptRoot 'Spectra.Bootstrap.ps1')
. (Join-Path $PSScriptRoot 'PortableSnapshot.Catalog.ps1')
$root=Get-SpectraBootstrapProductRoot;$temp=Join-Path ([IO.Path]::GetTempPath()) ('spectra-bootstrap-'+[guid]::NewGuid().ToString('N'));$passed=0
function Assert-Equal($A,$B,[string]$Code){if($A-cne$B){throw $Code}}
try{
  New-Item -ItemType Directory -Path $temp|Out-Null;$registry=Join-Path $temp 'projects with spaces';$config=Join-Path $temp 'config with spaces'
  $plan=Initialize-SpectraProjectRegistry -RegistryRoot $registry -ObservedAt '2031-01-01T00:00:00Z';Assert-Equal $plan.status 'PLANNED' 'BOOTSTRAP_PLAN_INVALID';$passed++
  $created=Initialize-SpectraBootstrapRoots -ConfigRoot $config -RegistryRoot $registry -ObservedAt '2031-01-01T00:00:00Z' -Apply;Assert-Equal $created.status 'INITIALIZED' 'BOOTSTRAP_CREATE_INVALID';$passed++
  $repeat=Initialize-SpectraProjectRegistry -RegistryRoot $registry -ObservedAt '2031-01-01T00:00:00Z' -Apply;Assert-Equal $repeat.status 'ALREADY_INITIALIZED' 'BOOTSTRAP_INIT_NOT_IDEMPOTENT';$passed++
  $doctor=Invoke-SpectraDoctor -ProductRoot $root -RegistryRoot $registry -ConfigRoot $config -Version $Version;Assert-Equal $doctor.status 'PASS' 'BOOTSTRAP_DOCTOR_FAILED';Assert-Equal $doctor.writes_performed $false 'BOOTSTRAP_DOCTOR_WROTE';if((Get-SpectraPlatform)-eq'windows'){Assert-Equal $doctor.windows_gate 'PASS' 'BOOTSTRAP_WINDOWS_GATE_FAILED';Assert-Equal $doctor.macos_gate 'MACOS_RUNNER_EVIDENCE_MISSING' 'BOOTSTRAP_MACOS_CLAIM_INVALID'};$passed++
  $binding=Get-SpectraReleaseBinding $root $Version;$workspace=Join-Path $registry 'customer-a';& (Join-Path $PSScriptRoot 'New-CustomerWorkspace.ps1') -Destination $workspace -Profile implementation -ExpectedBlueprintVersion $Version -CustomerAlias 'SYNTHETIC-A' -ProductRoot $root|Out-Null;$catalogFixture=Join-Path $temp 'snapshot-fixture';& (Join-Path $PSScriptRoot 'New-SyntheticPortableSnapshotCatalog.ps1') -Destination $catalogFixture|Out-Null;$catalog=Read-PortableJson (Join-Path $catalogFixture 'catalog.json');$project=$catalog.customers[0].projects[0];$release=Read-PortableJson (Join-Path $catalogFixture ($project.release_manifest_path-replace'/',[IO.Path]::DirectorySeparatorChar));$sourceSnapshot=Join-Path (Split-Path -Parent (Join-Path $catalogFixture ($project.release_manifest_path-replace'/',[IO.Path]::DirectorySeparatorChar))) $release.snapshot_path;$incoming=Join-Path $workspace 'incoming-snapshot.json';Copy-Item $sourceSnapshot $incoming;$snapshotObject=Read-PortableJson $incoming;$workspaceObject=Read-SpectraBootstrapJson (Join-Path $workspace 'workspace.yaml');$snapshotObject.customer_id=$workspaceObject.customer_id;$snapshotObject.project_id='PRJ-SYN-A';Write-PortableJson $incoming $snapshotObject
  $registered=Register-SpectraProject -RegistryRoot $registry -Workspace $workspace -WorkspaceId 'WS-SYN-CUSTOMER-A' -ProjectId 'PRJ-SYN-A' -Profile implementation -Mode new -Binding $binding -ObservedAt '2031-01-01T00:00:00Z' -ProductRoot $root;Assert-Equal $registered.relative_path 'customer-a' 'BOOTSTRAP_RELATIVE_PATH_INVALID';$passed++
  $registryHash=(Get-FileHash (Join-Path $registry 'spectra-projects.json')).Hash;$again=Register-SpectraProject -RegistryRoot $registry -Workspace $workspace -WorkspaceId 'WS-SYN-CUSTOMER-A' -ProjectId 'PRJ-SYN-A' -Profile implementation -Mode new -Binding $binding -ObservedAt '2031-01-01T00:00:00Z' -ProductRoot $root;Assert-Equal $again.status 'ALREADY_REGISTERED' 'BOOTSTRAP_REGISTER_NOT_IDEMPOTENT';Assert-Equal (Get-FileHash (Join-Path $registry 'spectra-projects.json')).Hash $registryHash 'BOOTSTRAP_REGISTRY_CHANGED';$passed++
  $handoff=New-SpectraTwinHandoff -Workspace $workspace -WorkspaceId 'WS-SYN-CUSTOMER-A' -ProjectId 'PRJ-SYN-A' -SnapshotPath $incoming -Binding $binding -ObservedAt '2031-01-01T01:00:00Z';Assert-Equal $handoff.status 'CREATED' 'BOOTSTRAP_HANDOFF_FAILED';Test-SpectraTwinHandoff $workspace|Out-Null;$passed++
  $handoffHash=(Get-FileHash (Join-Path $workspace 'twin-handoff.json')).Hash;$same=New-SpectraTwinHandoff -Workspace $workspace -WorkspaceId 'WS-SYN-CUSTOMER-A' -ProjectId 'PRJ-SYN-A' -SnapshotPath $incoming -Binding $binding -ObservedAt '2031-01-01T01:00:00Z';Assert-Equal $same.status 'ALREADY_CURRENT' 'BOOTSTRAP_HANDOFF_NOT_IDEMPOTENT';Assert-Equal (Get-FileHash (Join-Path $workspace 'twin-handoff.json')).Hash $handoffHash 'BOOTSTRAP_HANDOFF_CHANGED';$passed++
  $registryObject=Read-SpectraBootstrapJson (Join-Path $registry 'spectra-projects.json');Test-SpectraProjectRegistry $registryObject|Out-Null;$passed++
  $macDefaults=Get-SpectraDefaultRoots -HomePath '/Users/Spectra User' -XdgConfigHome '' -XdgDataHome '' -Platform macos;Assert-Equal $macDefaults.config_root '/Users/Spectra User/.config/spectra' 'BOOTSTRAP_MAC_CONFIG_DEFAULT_INVALID';Assert-Equal $macDefaults.registry_root '/Users/Spectra User/.local/share/spectra' 'BOOTSTRAP_MAC_DATA_DEFAULT_INVALID';$passed++
  $xdg=Get-SpectraDefaultRoots -HomePath '/Users/unused' -XdgConfigHome '/Volumes/Case Sensitive/Config' -XdgDataHome '/Volumes/Case Sensitive/Data' -Platform macos;Assert-Equal $xdg.config_root '/Volumes/Case Sensitive/Config/spectra' 'BOOTSTRAP_XDG_CONFIG_INVALID';Assert-Equal $xdg.registry_root '/Volumes/Case Sensitive/Data/spectra' 'BOOTSTRAP_XDG_DATA_INVALID';if(Test-SpectraPathPrefix -Root '/Users/Case' -Path '/users/Case/project' -Platform macos){throw 'BOOTSTRAP_MAC_CASE_INSENSITIVE'};$passed++
  if($passed-ne11){throw 'BOOTSTRAP_POSITIVE_COUNT_INVALID'};Write-Host "PASS: $passed Bootstrap-/Doctor-/Registry-/Twin-Handoff-/XDG-Pruefungen."
}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
