[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';$x=Get-Content (Join-Path $Path 'project-story.json') -Raw|ConvertFrom-Json
$valid=@($x.offer.id)+@($x.pages|ForEach-Object id)+@($x.tickets|ForEach-Object id)+@($x.evidence|ForEach-Object id)+@($x.sessions|ForEach-Object id)+@($x.decisions|ForEach-Object id)+@($x.deliverables|ForEach-Object id)
$inverse=@{'offer-page'='page-offer';'page-offer'='offer-page';'page-ticket'='ticket-page';'ticket-page'='page-ticket';'ticket-evidence'='evidence-ticket';'evidence-ticket'='ticket-evidence';'page-session'='session-page';'session-page'='page-session';'ticket-decision'='decision-ticket';'decision-ticket'='ticket-decision';'ticket-deliverable'='deliverable-ticket';'deliverable-ticket'='ticket-deliverable'}
foreach($p in @($x.pages)){$txt=Get-Content (Join-Path $Path $p.sourcePath) -Raw;if($txt -notmatch "parent:\s*$([regex]::Escape([string]$p.parent))"){throw 'PORTABLE_PAGE_METADATA_PARENT'}}
$keys=@();foreach($e in @($x.graph)){if($valid -notcontains $e.from -or $valid -notcontains $e.to){throw 'PORTABLE_GRAPH_ORPHAN'};if(-not $inverse.ContainsKey($e.type)){throw 'PORTABLE_GRAPH_RELATION'};$key="$($e.from)|$($e.to)|$($e.type)";if($keys -contains $key){throw 'PORTABLE_GRAPH_DUPLICATE'};$keys+=$key}
foreach($e in @($x.graph)){if(@($x.graph|Where-Object {$_.from -eq $e.to -and $_.to -eq $e.from -and $_.type -eq $inverse[$e.type]}).Count -ne 1){throw 'PORTABLE_GRAPH_INVERSE'}}
foreach($h in @($x.hypercare)){if(@($h.tickets).Count -eq 0 -or [string]::IsNullOrWhiteSpace($h.diagnosis) -or [string]::IsNullOrWhiteSpace($h.fix) -or [string]::IsNullOrWhiteSpace($h.retest) -or [string]::IsNullOrWhiteSpace($h.comment) -or @($h.evidence).Count -eq 0){throw 'PORTABLE_HYPERCARE_FIELDS'};foreach($tid in @($h.tickets)){if(@($x.tickets|Where-Object id -eq $tid).Count -ne 1){throw 'PORTABLE_HYPERCARE_TICKET_REFERENCE'}}}
Write-Host 'PASS: Portable structural gates.'
