[CmdletBinding()]param()
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0;$root=[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$sandbox=Join-Path ([System.IO.Path]::GetTempPath()) ('spectra-final-release-'+[Guid]::NewGuid().ToString('N'));$fixture=Join-Path $sandbox 'repo';$workspace=Join-Path $sandbox 'workspace';$version='9.6.0-alpha.1';$generator=Join-Path $root 'automation\New-CustomerWorkspace.ps1'
function Invoke-Tool([string]$File,[string[]]$Arguments){$i=New-Object System.Diagnostics.ProcessStartInfo;$i.FileName=$File;$i.Arguments=(($Arguments|ForEach-Object{if($_ -like '-*'){$_}else{'"'+$_.Replace('"','\"')+'"'}})-join ' ');$i.UseShellExecute=$false;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=New-Object System.Diagnostics.Process;$p.StartInfo=$i;[void]$p.Start();$out=$p.StandardOutput.ReadToEnd();$err=$p.StandardError.ReadToEnd();$p.WaitForExit();$c=$p.ExitCode;if($c-ne 0){Write-Host $out;Write-Host $err};$p.Dispose();return $c}
function Invoke-Generator([string[]]$GeneratorArguments){Invoke-Tool 'powershell.exe' (@('-NoProfile','-ExecutionPolicy','Bypass','-File',$generator)+$GeneratorArguments)}
try{
 [void](New-Item -ItemType Directory -Path $fixture -Force);foreach($rel in @('AGENTS.md','README.md','automation','catalogs','contract','examples\minimal-contract','schemas','tests\invalid','release')){$src=Join-Path $root $rel;$dst=Join-Path $fixture $rel;$d=Split-Path -Parent $dst;if(-not(Test-Path $d)){[void](New-Item -ItemType Directory -Path $d -Force)};Copy-Item $src $dst -Recurse -Force};& git -C $fixture init -b main|Out-Null;&git -C $fixture config core.autocrlf false;&git -C $fixture config user.email 'spectra-fixture@example.invalid';&git -C $fixture config user.name 'Spectra Fixture';&git -C $fixture remote add origin 'https://github.com/sivla/BCProjectOS.git';&git -C $fixture add -A;&git -C $fixture commit -m source|Out-Null;&git -C $fixture checkout -- .;$source=(&git -C $fixture rev-parse HEAD).Trim();&powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $fixture 'automation\New-ReleaseCandidate.ps1') -Version $version -ReleaseDate 2026-07-11 -SourceCommit $source|Out-Null;&git -C $fixture add release/versions/$version;&git -C $fixture commit -m manifest|Out-Null;&powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $fixture 'automation\Promote-ReleaseCandidate.ps1') -RepositoryRoot $fixture -Version $version -SyntheticRepository|Out-Null
 if((Invoke-Generator @('-Destination',$workspace,'-Profile','implementation','-CustomerAlias','alpha-fixture','-ExpectedBlueprintVersion',$version,'-ProductRoot',$fixture))-ne 0){throw 'POSITIVE_FAILED'};$ws=Get-Content (Join-Path $workspace 'workspace.yaml') -Raw|ConvertFrom-Json;$bindPath=Join-Path $workspace 'governance\policies\release-binding.json';$bind=Get-Content $bindPath -Raw|ConvertFrom-Json;if([string]$ws.title -ne 'alpha-fixture' -or [string]$ws.blueprint_version -ne $version -or [string]$bind.binding_status -ne 'BOUND'){throw 'METADATA_FAILED'};&powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'automation\Test-ConsumerBinding.ps1') -Path $bindPath -RepositoryRoot $fixture;if($LASTEXITCODE-ne 0){throw 'BINDING_FAILED'};Write-Host 'PASS: Verified final synthetic release installs.'
 if((Invoke-Generator @('-Destination',(Join-Path $sandbox 'candidate'),'-Profile','implementation','-CustomerAlias','alpha-fixture','-ExpectedBlueprintVersion',$version))-eq 0){throw 'CANDIDATE_ACCEPTED'};Write-Host 'PASS: Candidate blocked.'
 if((Invoke-Generator @('-Destination',(Join-Path $sandbox 'bad'),'-Profile','implementation','-CustomerAlias','bad alias','-ExpectedBlueprintVersion',$version,'-ProductRoot',$fixture))-eq 0){throw 'ALIAS_ACCEPTED'};if((Invoke-Generator @('-Destination',$workspace,'-Profile','implementation','-CustomerAlias','alpha-fixture','-ExpectedBlueprintVersion',$version,'-ProductRoot',$fixture))-eq 0){throw 'EXISTING_ACCEPTED'};if((Invoke-Generator @('-Destination',(Join-Path $sandbox 'mixed'),'-Profile','implementation','-CustomerAlias','alpha-fixture','-ExpectedBlueprintVersion',$version,'-ProductRoot',$fixture,'-SyntheticFixture'))-eq 0){throw 'MIXED_ACCEPTED'};Write-Host 'PASS: Alias, existing target and mixed mode blocked.'
 &git -C $fixture tag -d "spectra-v$version"|Out-Null;if((Invoke-Generator @('-Destination',(Join-Path $sandbox 'missing-tag'),'-Profile','implementation','-CustomerAlias','alpha-fixture','-ExpectedBlueprintVersion',$version,'-ProductRoot',$fixture))-eq 0){throw 'MISSING_TAG_ACCEPTED'};Write-Host 'PASS: Missing tag blocked.'
}finally{if(Test-Path $sandbox){Remove-Item $sandbox -Recurse -Force}}
