[CmdletBinding()]param()
$ErrorActionPreference='Stop';$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$tmp=Join-Path ([IO.Path]::GetTempPath()) ('spectra-validator-'+[guid]::NewGuid().ToString('N'));$repo=Join-Path $tmp 'repo';$ws=Join-Path $tmp 'workspace';New-Item -ItemType Directory -Force $repo|Out-Null
try {
 foreach($p in @('AGENTS.md','README.md','automation','catalogs','contract','examples\minimal-contract','schemas','tests\invalid','release')){Copy-Item (Join-Path $root $p) (Join-Path $repo $p) -Recurse -Force}
 git -C $repo init -b main|Out-Null;git -C $repo remote add origin https://github.com/sivla/BCProjectOS.git;git -C $repo config core.autocrlf false;git -C $repo config user.email test@example.invalid;git -C $repo config user.name SpectraFixture;git -C $repo add .;git -C $repo commit -m source|Out-Null
 Push-Location $repo; & powershell -NoProfile -ExecutionPolicy Bypass -File automation\New-ReleaseCandidate.ps1 -Version 0.1.0-alpha.2 -ReleaseDate 2026-07-12|Out-Null;git add release;git commit -m candidate|Out-Null;& powershell -NoProfile -ExecutionPolicy Bypass -File automation\Promote-ReleaseCandidate.ps1 -RepositoryRoot $repo -Version 0.1.0-alpha.2 -SyntheticRepository|Out-Null;Pop-Location
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\New-CustomerWorkspace.ps1') -Destination $ws -Profile implementation -CustomerAlias validator-fixture -ExpectedBlueprintVersion 0.1.0-alpha.2 -ProductRoot $repo|Out-Null
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Test-CustomerWorkspace.ps1') -Path $ws -ProductRoot $repo|Out-Null
 $wsObj=Get-Content (Join-Path $ws 'workspace.yaml') -Raw|ConvertFrom-Json;$tempBlob=Join-Path $ws 'external-files\originals\temp.bin';New-Item -ItemType Directory -Force (Split-Path $tempBlob)|Out-Null;[IO.File]::WriteAllBytes($tempBlob,[byte[]](1,2,3));$hash=(Get-FileHash $tempBlob -Algorithm SHA256).Hash.ToLowerInvariant();$blobRel="external-files/originals/sha256/$($hash.Substring(0,2))/$hash";$blob=Join-Path $ws ($blobRel -replace '/','\');New-Item -ItemType Directory -Force (Split-Path $blob)|Out-Null;Move-Item $tempBlob $blob;$ext=[ordered]@{schema_version=1;id=('FILE-'+$wsObj.id.Substring(4));customer_id=$wsObj.customer_id;entity_type='external_file';title='Synthetische Datei';lifecycle_status='draft';created_at=(Get-Date).ToUniversalTime().ToString('o');relations=@();sha256=$hash;size_bytes=3;media_type='application/octet-stream';original_name='fixture.bin';blob_path=$blobRel};$ext|ConvertTo-Json|Set-Content (Join-Path $ws 'external-files\register\file.json') -Encoding utf8;$ev=[ordered]@{schema_version=1;id=('EVD-'+$wsObj.id.Substring(4));customer_id=$wsObj.customer_id;entity_type='evidence';title='Synthetischer UAT-Nachweis';lifecycle_status='draft';created_at=(Get-Date).ToUniversalTime().ToString('o');relations=@();evidence_type='uat';evidence_refs=@($ext.id)};$ev|ConvertTo-Json|Set-Content (Join-Path $ws 'evidence\uat.json') -Encoding utf8;& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Test-CustomerWorkspace.ps1') -Path $ws -ProductRoot $repo|Out-Null;if($LASTEXITCODE -ne 0){throw 'SPECIALIZED_FIXTURE_REJECTED'}
 $wsObj=Get-Content (Join-Path $ws 'workspace.yaml') -Raw|ConvertFrom-Json;$entity=[ordered]@{schema_version=1;id='PRJ-invalid';customer_id=$wsObj.customer_id;entity_type='project';title='Ungültig';lifecycle_status='draft';created_at=(Get-Date).ToUniversalTime().ToString('o');relations=@()};$entity|ConvertTo-Json -Depth 8|Set-Content (Join-Path $ws 'projects\project.json') -Encoding utf8;& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Test-CustomerWorkspace.ps1') -Path $ws -ProductRoot $repo|Out-Null;$entityFailed=($LASTEXITCODE -ne 0);if(-not $entityFailed){throw 'ENTITY_CONTRACT_ACCEPTED'}
 $before=(Get-FileHash (Join-Path $ws 'workspace.yaml')).Hash;Add-Content (Join-Path $ws 'governance\catalogs\statuses.yaml') "`ninvalid: true";& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'automation\Test-CustomerWorkspace.ps1') -Path $ws -ProductRoot $repo|Out-Null;$failed=($LASTEXITCODE -ne 0);if(-not $failed){throw 'CATALOG_DRIFT_ACCEPTED'};if((Get-FileHash (Join-Path $ws 'workspace.yaml')).Hash -ne $before){throw 'VALIDATOR_MUTATED_WORKSPACE'};Write-Host 'PASS: install-to-read-only-validation and catalog-drift negative gate.'
} finally {Pop-Location -ErrorAction SilentlyContinue;if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue}}
