[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$root=[IO.Path]::GetFullPath($Path);$file=Join-Path $root 'setup-permissions-data.json';if(-not(Test-Path $file -PathType Leaf)){throw 'SETUP_DATA_RECORD_MISSING'}
$before=(Get-FileHash $file -Algorithm SHA256).Hash;$x=Get-Content $file -Raw|ConvertFrom-Json
. (Join-Path $PSScriptRoot 'Spectra.JsonSchema.ps1');$schema=Get-Content (Join-Path $PSScriptRoot '..\schemas\setup-permissions-data.schema.json') -Raw|ConvertFrom-Json
try{Test-SpectraJsonSchema -Value $x -Schema $schema -RootSchema $schema -Path 'root'}catch{throw 'SETUP_DATA_SCHEMA_INVALID'}
$ids=@{};foreach($collection in @($x.setup_steps,$x.roles,$x.data_templates,$x.migration_waves)){foreach($o in $collection){if($ids.ContainsKey([string]$o.id)){throw 'SETUP_DATA_DUPLICATE_ID'};$ids[[string]$o.id]=$true}}
$steps=@{};foreach($s in $x.setup_steps){$steps[[string]$s.id]=$s};foreach($s in $x.setup_steps){foreach($d in $s.depends_on){if(-not$steps.ContainsKey([string]$d)){throw 'SETUP_DEPENDENCY_UNKNOWN'};if([int]$steps[[string]$d].sequence-ge[int]$s.sequence){throw 'SETUP_SEQUENCE_INVALID'}};foreach($p in $s.parameters){if($p.value_classification-notin@('standard','customer_parameter','localization_or_tax_confirmation')){throw 'SETUP_CLASSIFICATION_UNKNOWN'};if(-not$ids.ContainsKey([string]$p.owner_role)){throw 'SETUP_OWNER_UNKNOWN'}}}
$roleById=@{};foreach($r in $x.roles){$roleById[[string]$r.id]=$r;if([string]::IsNullOrWhiteSpace([string]$r.positive_probe)-or[string]::IsNullOrWhiteSpace([string]$r.denied_probe)){throw 'SOD_PROBE_MISSING'}};foreach($r in $x.roles){foreach($f in $r.forbidden_with){if(-not$roleById.ContainsKey([string]$f)){throw 'SOD_ROLE_UNKNOWN'};if(-not(@($roleById[[string]$f].forbidden_with)-contains[string]$r.id)){throw 'SOD_CONFLICT_ASYMMETRIC'}}}
$templateById=@{};$types=@();foreach($t in $x.data_templates){$templateById[[string]$t.id]=$t;$types+=@([string]$t.type);foreach($ref in $t.reference_rules){if(-not(@($x.data_templates.id)-contains[string]$ref)){throw 'DATA_REFERENCE_INVALID'}}};if(@($types|Sort-Object -Unique).Count-ne8){throw 'DATA_TEMPLATE_SET_INVALID'}
$expectedWave=1;foreach($w in ($x.migration_waves|Sort-Object sequence)){if([int]$w.sequence-ne$expectedWave){throw 'DATA_WAVE_SEQUENCE_INVALID'};$expectedWave++;foreach($ref in $w.template_refs){if(-not$templateById.ContainsKey([string]$ref)){throw 'DATA_REFERENCE_INVALID'}};if([int]$w.accepted_count+[int]$w.rejected_count-ne[int]$w.source_count){throw 'DATA_CONTROL_TOTAL_MISMATCH'};if([string]$w.control_total-notmatch'^[a-f0-9]{64}$'){throw 'DATA_DIGEST_INVALID'}}
$raw=Get-Content $file -Raw;if($raw-match'(?i)(credential_marker|tenant_marker|customer_content_marker)'){throw 'SETUP_DATA_CUSTOMER_OR_SECRET_MARKER'}
if((Get-FileHash $file -Algorithm SHA256).Hash-ne$before){throw 'SETUP_DATA_VALIDATOR_MUTATED_SOURCE'}
Write-Host 'PASS: Setupreihenfolge, Parameter, SoD, Datenwellen und Readiness sind konsistent.'
