$ErrorActionPreference='Stop';$source=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$temp=Join-Path $env:TEMP ('spectra-skill-negative-'+[guid]::NewGuid().ToString('N'))
function Write-Utf8([string]$p,[string]$t){[IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($false))}
function Invoke-Exact([string]$root){$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName='powershell.exe';$psi.Arguments="-NoProfile -ExecutionPolicy Bypass -File `"$PSScriptRoot\Run-SpectraSkillCatalogExact.ps1`" -Root `"$root`"";$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=[Diagnostics.Process]::Start($psi);$o=$p.StandardOutput.ReadToEnd().Trim();$e=$p.StandardError.ReadToEnd().Trim();$p.WaitForExit();[pscustomobject]@{Exit=$p.ExitCode;Out=$o;Err=$e}}
$cases=@(
  @{code='SKILL_CATALOG_DIRECTORY_SET_INVALID';m={param($r)Remove-Item (Join-Path $r 'skills\validate-project-snapshot') -Recurse -Force}},
  @{code='SKILL_NAME_MISMATCH:process-project-intake';m={param($r)$p=Join-Path $r 'skills\process-project-intake\SKILL.md';Write-Utf8 $p ((Get-Content $p -Raw)-replace'name: process-project-intake','name: wrong-name')}},
  @{code='SKILL_PLACEHOLDER_PRESENT:research-business-central';m={param($r)Add-Content (Join-Path $r 'skills\research-business-central\SKILL.md') '`nTODO'}},
  @{code='SKILL_REQUIRED_FILE_MISSING:render-project-documentation';m={param($r)Remove-Item (Join-Path $r 'skills\render-project-documentation\references\contract.md')}},
  @{code='SKILL_IMPLICIT_POLICY_INVALID:operate-bc-pilot-sandbox';m={param($r)$p=Join-Path $r 'skills\operate-bc-pilot-sandbox\agents\openai.yaml';Write-Utf8 $p ((Get-Content $p -Raw)-replace'allow_implicit_invocation: false','allow_implicit_invocation: true')}},
  @{code='SKILL_CATALOG_DUPLICATE_TRIGGER_PHRASE';m={param($r)$p=Join-Path $r 'contract\skills\catalog.json';$x=Get-Content $p -Raw|ConvertFrom-Json;$x.skills[1].trigger_phrase=$x.skills[0].trigger_phrase;Write-Utf8 $p (($x|ConvertTo-Json -Depth 10)+"`n")}},
  @{code='SKILL_CLUTTER_FORBIDDEN:initialize-customer-workspace';m={param($r)Write-Utf8 (Join-Path $r 'skills\initialize-customer-workspace\README.md') 'clutter'}},
  @{code='SKILL_CUSTOMER_MARKER_FORBIDDEN:capture-bc-click-guide';m={param($r)Add-Content (Join-Path $r 'skills\capture-bc-click-guide\references\contract.md') '`nUABC'}},
  @{code='SKILL_SECRET_VALUE_FORBIDDEN:materialize-atlassian-project';m={param($r)Add-Content (Join-Path $r 'skills\materialize-atlassian-project\references\contract.md') '`napi_token="not-a-secret"'}},
  @{code='SKILL_SAFETY_CONTRACT_INCOMPLETE:manage-project-status-budget';m={param($r)$p=Join-Path $r 'skills\manage-project-status-budget\references\contract.md';Write-Utf8 $p ((Get-Content $p -Raw)-replace'Stop-Codes:','Fehler:')}},
  @{code='SKILL_CATALOG_DIRECTORY_SET_INVALID';m={param($r)New-Item -ItemType Directory -Path (Join-Path $r 'skills\extra-skill')|Out-Null}},
  @{code='SKILL_DEFAULT_PROMPT_MISSING_TRIGGER:index-project-repository';m={param($r)$p=Join-Path $r 'skills\index-project-repository\agents\openai.yaml';Write-Utf8 $p ((Get-Content $p -Raw)-replace'\$index-project-repository','repository skill')}},
  @{code='SKILL_REFERENCE_NOT_LINKED:run-bc-uat-training-handover';m={param($r)$p=Join-Path $r 'skills\run-bc-uat-training-handover\SKILL.md';Write-Utf8 $p ((Get-Content $p -Raw)-replace'\(references/contract\.md\)','(references/missing.md)')}}
)
try{$i=0;foreach($c in $cases){$i++;$r=Join-Path $temp "$i";New-Item -ItemType Directory -Path $r|Out-Null;Copy-Item (Join-Path $source 'skills') $r -Recurse;New-Item -ItemType Directory -Path (Join-Path $r 'contract\skills') -Force|Out-Null;Copy-Item (Join-Path $source 'contract\skills\catalog.json') (Join-Path $r 'contract\skills\catalog.json');New-Item -ItemType Directory -Path (Join-Path $r 'schemas')|Out-Null;Copy-Item (Join-Path $source 'schemas\skill-catalog.schema.json') (Join-Path $r 'schemas\skill-catalog.schema.json');&$c.m $r;$res=Invoke-Exact $r;if($res.Exit-ne1-or$res.Err-ne''-or$res.Out-cne$c.code){throw "SKILL_NEGATIVE_FAILED:$i expected=$($c.code) exit=$($res.Exit) out=$($res.Out) err=$($res.Err)"}};Write-Host "PASS: $($cases.Count) isolierte Skillkatalog-Negativfälle."}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force}}
