[CmdletBinding()]
param([ValidatePattern('^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$')][string]$Version='1.0.0')
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$temp=Join-Path $env:TEMP ('spectra-candidate-binding-'+[guid]::NewGuid().ToString('N'));$base=Join-Path $temp 'base';$version=$Version;$utf8=New-Object Text.UTF8Encoding($false)
. (Join-Path $PSScriptRoot 'Release.Common.ps1')
function Copy-Product([string]$d){New-Item -ItemType Directory -Force $d|Out-Null;foreach($rel in @('AGENTS.md','README.md','automation','catalogs','contract','examples\minimal-contract','schemas','skills','tests\invalid','release')){$src=Join-Path $root $rel;$dst=Join-Path $d $rel;$parent=Split-Path -Parent $dst;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Force $parent|Out-Null};Copy-Item $src $dst -Recurse -Force};$sameVersionEvidence=Join-Path $d "release\versions\$version";if(Test-Path -LiteralPath $sameVersionEvidence){Remove-Item -LiteralPath $sameVersionEvidence -Recurse -Force}}
function Write-Manifest([string]$repo,$value){[IO.File]::WriteAllText((Join-Path $repo "release\versions\$version\release-manifest.json"),(($value|ConvertTo-Json -Depth 30)+"`n"),$utf8)}
function Mutate-Manifest([string]$repo,[scriptblock]$mutation){$p=Join-Path $repo "release\versions\$version\release-manifest.json";$m=Get-Content $p -Raw|ConvertFrom-Json;&$mutation $m;Write-Manifest $repo $m}
function Rewrite-LegacyPayload([string]$repo){$p=Join-Path $repo "release\versions\$version\release-manifest.json";$m=Get-Content $p -Raw|ConvertFrom-Json;$scope=Get-BCProjectOSReleaseScope -Root $repo -Revision ([string]$m.source_commit);$records=@(Get-BCProjectOSGitPayloadRecords -Root $repo -Revision ([string]$m.source_commit) -Scope $scope);$text=Get-BCProjectOSChecksumsText -Records $records;[IO.File]::WriteAllText((Join-Path $repo "release\versions\$version\checksums.sha256"),$text,$utf8);$m.payload.files=$records;$m.payload.file_count=$records.Count;$m.payload.bundle_digest=Get-BCProjectOSTextSha256 -Text $text;Write-Manifest $repo $m}
function Start-Validation([string]$repo){$s=[Diagnostics.ProcessStartInfo]::new();$s.FileName='powershell.exe';$s.Arguments="-NoProfile -ExecutionPolicy Bypass -File `"$repo\automation\Test-ReleaseCandidate.ps1`" -Version $version -SkipProductContract";$s.UseShellExecute=$false;$s.RedirectStandardOutput=$true;$s.RedirectStandardError=$true;[Diagnostics.Process]::Start($s)}
function Complete-Validation([Diagnostics.Process]$p){$o=$p.StandardOutput.ReadToEnd();$e=$p.StandardError.ReadToEnd();$p.WaitForExit();[pscustomobject]@{Exit=$p.ExitCode;Output=$o;Error=$e}}
function Invoke-Validation([string]$repo){Complete-Validation (Start-Validation $repo)}
try{
  Copy-Product $base;&git -C $base init -b main|Out-Null;&git -C $base config core.autocrlf false;&git -C $base config user.email candidate@example.invalid;&git -C $base config user.name 'Spectra Candidate';&git -C $base add -A;&git -C $base commit -m source|Out-Null
  $source=(&git -C $base rev-parse HEAD).Trim();$tree=(&git -C $base rev-parse 'HEAD^{tree}').Trim();$savedPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';$invalid=@(&powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $base 'automation\New-ReleaseCandidate.ps1') -Version '01.0.0' -ReleaseDate 2026-07-12 -SourceCommit $source 2>&1);$invalidExit=$LASTEXITCODE;$ErrorActionPreference=$savedPreference;if($invalidExit-eq0){throw 'INVALID_STABLE_VERSION_ACCEPTED'};&powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $base 'automation\New-ReleaseCandidate.ps1') -Version $version -ReleaseDate 2026-07-12 -SourceCommit $source|Out-Null
  $manifest=Get-Content (Join-Path $base "release\versions\$version\release-manifest.json") -Raw|ConvertFrom-Json
  if([int]$manifest.schema_version-ne4-or$manifest.manifest_state-ne'candidate'-or$manifest.installable_blueprint-ne$false-or$manifest.consumer_mode-ne'CONTRACT_REFERENCE_ONLY'-or$null-ne$manifest.source_commit-or$null-ne$manifest.source_tree-or$manifest.candidate_source_commit-ne$source-or$manifest.candidate_source_tree-ne$tree-or@($manifest.payload.files|Where-Object{[string]$_.mode-notmatch'^100(644|755)$'}).Count-ne0){throw 'BOUND_CANDIDATE_GENERATION_FAILED'}
  &git -C $base add release/versions/$version;&git -C $base commit -m candidate|Out-Null;$positive=Invoke-Validation $base;if($positive.Exit-ne0){throw "BOUND_CANDIDATE_POSITIVE_FAILED:$($positive.Output):$($positive.Error)"}
  $cases=@(
    @{name='null-source';code='CANDIDATE_SOURCE_COMMIT_MISSING';m={param($r)Mutate-Manifest $r {param($x)$x.candidate_source_commit=$null}}},
    @{name='missing-source';code='CANDIDATE_SOURCE_COMMIT_MISSING';m={param($r)Mutate-Manifest $r {param($x)$x.PSObject.Properties.Remove('candidate_source_commit')}}},
    @{name='premature-final-source';code='CANDIDATE_FINAL_SOURCE_PRESENT';m={param($r)Mutate-Manifest $r {param($x)$x.source_commit=('0'*40)}}},
    @{name='wrong-tree';code='CANDIDATE_SOURCE_TREE_MISMATCH';m={param($r)Mutate-Manifest $r {param($x)$x.candidate_source_tree=('0'*40)}}},
    @{name='installable';code='CANDIDATE_SCOPE_CLAIM_INVALID';m={param($r)Mutate-Manifest $r {param($x)$x.installable_blueprint=$true;$x.consumer_mode='INSTALLABLE_BLUEPRINT'}}},
    @{name='digest';code='RELEASE_BUNDLE_DIGEST_MISMATCH';m={param($r)Mutate-Manifest $r {param($x)$x.payload.bundle_digest=('0'*64)}}},
    @{name='payload';code='PAYLOAD_CHANGED_AFTER_SOURCE_COMMIT';m={param($r)[IO.File]::AppendAllText((Join-Path $r 'README.md'),'changed');&git -C $r add README.md;&git -C $r commit -m payload-change|Out-Null}},
    @{name='missing-mode';code='RELEASE_FILE_MODE_INVALID';m={param($r)Mutate-Manifest $r {param($x)$x.payload.files[0].PSObject.Properties.Remove('mode')}}},
    @{name='wrong-mode';code='RELEASE_FILE_MODE_MISMATCH';m={param($r)Mutate-Manifest $r {param($x)$x.payload.files[0].mode=if([string]$x.payload.files[0].mode-eq'100644'){'100755'}else{'100644'}}}},
    @{name='payload-mode';code='PAYLOAD_CHANGED_AFTER_SOURCE_COMMIT';m={param($r)&git -C $r update-index --chmod=+x README.md;&git -C $r commit -m payload-mode-change|Out-Null}},
    @{name='unexpected-version';code='RELEASE_VERSION_INVALID';m={param($r)Mutate-Manifest $r {param($x)$x.release_version='0.9.0'}}},
    @{name='self-reference';code='CANDIDATE_SOURCE_SELF_REFERENCE';m={param($r)$c=(&git -C $r rev-parse HEAD).Trim();$t=(&git -C $r rev-parse 'HEAD^{tree}').Trim();Mutate-Manifest $r {param($x)$x.candidate_source_commit=$c;$x.candidate_source_tree=$t}}},
    @{name='legacy';code='LEGACY_UNBOUND_CANDIDATE_REJECTED';m={param($r)Mutate-Manifest $r {param($x)$x.schema_version=2;$x.source_commit=$x.candidate_source_commit;$x.source_tree=$x.candidate_source_tree;$x.PSObject.Properties.Remove('candidate_source_commit');$x.PSObject.Properties.Remove('candidate_source_tree')}}}
  )
  $runs=@();foreach($c in $cases){$repo=Join-Path $temp $c.name;&git clone --no-local --quiet $base $repo;&$c.m $repo;$runs+=,[pscustomobject]@{kind='negative';name=$c.name;code=$c.code;process=(Start-Validation $repo)}}
  $legacy=Join-Path $temp 'legacy-final';&git clone --no-local --quiet $base $legacy;Mutate-Manifest $legacy {param($x)$x.schema_version=1;$x.manifest_state='final';$x.source_commit=$x.candidate_source_commit;$x.installable_blueprint=$true;$x.consumer_mode='INSTALLABLE_BLUEPRINT';$x.PSObject.Properties.Remove('source_tree');$x.PSObject.Properties.Remove('candidate_source_commit');$x.PSObject.Properties.Remove('candidate_source_tree')};Rewrite-LegacyPayload $legacy;$runs+=,[pscustomobject]@{kind='final';name='schema1';code='';process=(Start-Validation $legacy)}
  $schema2=Join-Path $temp 'schema2-final';&git clone --no-local --quiet $base $schema2;Mutate-Manifest $schema2 {param($x)$x.schema_version=2;$x.manifest_state='final';$x.source_commit=$x.candidate_source_commit;$x.source_tree=$x.candidate_source_tree;$x.installable_blueprint=$true;$x.consumer_mode='INSTALLABLE_BLUEPRINT';$x.PSObject.Properties.Remove('candidate_source_commit');$x.PSObject.Properties.Remove('candidate_source_tree')};Rewrite-LegacyPayload $schema2;$runs+=,[pscustomobject]@{kind='final';name='schema2';code='';process=(Start-Validation $schema2)}
  $schema3=Join-Path $temp 'schema3-final';&git clone --no-local --quiet $base $schema3;Mutate-Manifest $schema3 {param($x)$x.schema_version=3;$x.manifest_state='final';$x.source_commit=$x.candidate_source_commit;$x.source_tree=$x.candidate_source_tree;$x.installable_blueprint=$true;$x.consumer_mode='INSTALLABLE_BLUEPRINT';$x.PSObject.Properties.Remove('candidate_source_commit');$x.PSObject.Properties.Remove('candidate_source_tree')};Rewrite-LegacyPayload $schema3;$runs+=,[pscustomobject]@{kind='final';name='schema3';code='';process=(Start-Validation $schema3)}
  $residual=Join-Path $temp 'residual-final';&git clone --no-local --quiet $base $residual;Mutate-Manifest $residual {param($x)$x.manifest_state='final';$x.source_commit=$x.candidate_source_commit;$x.source_tree=$x.candidate_source_tree;$x.installable_blueprint=$true;$x.consumer_mode='INSTALLABLE_BLUEPRINT'};$runs+=,[pscustomobject]@{kind='negative';name='residual';code='FINAL_CANDIDATE_PROVENANCE_PRESENT';process=(Start-Validation $residual)}
  foreach($run in $runs){$result=Complete-Validation $run.process;if($run.kind-eq'final'){if($result.Exit-ne0){throw "FINAL_COMPATIBILITY_FAILED:$($run.name):$($result.Output):$($result.Error)"}}elseif($result.Exit-ne1-or$result.Output-notmatch("\["+[regex]::Escape($run.code)+"\]")){throw "CANDIDATE_NEGATIVE_FAILED:$($run.name):$($result.Exit):$($result.Output):$($result.Error)"}}
  Write-Host "PASS: Gebundener stabiler, nicht installierbarer Candidate, ungueltige Version, $($cases.Count) negative Faelle, Residualfeldblockierung und Schema-v1-/Schema-v2-/Schema-v3-Finalkompatibilitaet."
}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
