[CmdletBinding()]param([string]$ProductRoot,[string]$EvidencePath)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$sourceRoot=if($ProductRoot){[IO.Path]::GetFullPath($ProductRoot)}else{[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))};$version='0.14.0-alpha.1';$tag="spectra-v$version";$temp=Join-Path $env:TEMP ('spectra-v1-pilots-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$root=Join-Path $temp 'product-release'
function Assert-Exit([string]$Code){if($LASTEXITCODE-ne0){throw $Code}}
function Install-Pilot([string]$Profile,[string]$Destination){& (Join-Path $root 'automation\New-CustomerWorkspace.ps1') -Destination $Destination -Profile $Profile -CustomerAlias ("pilot-$Profile") -ExpectedBlueprintVersion $version -ProductRoot $root|Out-Null;Assert-Exit "PILOT_INSTALL_FAILED:$Profile";& (Join-Path $root 'automation\Test-CustomerWorkspace.ps1') -Path $Destination -ProductRoot $root|Out-Null;Assert-Exit "PILOT_WORKSPACE_INVALID:$Profile"}
function Backup-Restore-Pilot([string]$Profile,[string]$Workspace){$backup=Join-Path $temp "$Profile-backup";$restore=Join-Path $temp "$Profile-restored";& (Join-Path $root 'automation\Backup-Workspace.ps1') -Source $Workspace -Destination $backup|Out-Null;& (Join-Path $root 'automation\Restore-Workspace.ps1') -Backup $backup -Destination $restore|Out-Null;& (Join-Path $root 'automation\Test-CustomerWorkspace.ps1') -Path $restore -ProductRoot $root|Out-Null;Assert-Exit "PILOT_RESTORE_INVALID:$Profile";return $restore}
try{
 &git -c core.longpaths=true clone --no-local --quiet --branch $tag $sourceRoot $root;Assert-Exit 'PILOT_RELEASE_CLONE_FAILED';&git -C $root remote set-url origin 'https://github.com/sivla/BCProjectOS.git';Assert-Exit 'PILOT_RELEASE_REMOTE_FAILED'
 & (Join-Path $root 'automation\Test-ReleaseCandidate.ps1') -Version $version|Out-Null;Assert-Exit 'PILOT_RELEASE_NOT_BOUND';$tagCommit=(&git -C $root rev-parse "refs/tags/$tag^{commit}").Trim()
 $impl=Join-Path $temp 'implementation';Install-Pilot 'implementation' $impl;$implFlow=Join-Path $impl 'pilot-evidence';New-Item -ItemType Directory $implFlow|Out-Null
 & (Join-Path $root 'automation\New-SyntheticEngagementFitStandard.ps1') -Destination (Join-Path $implFlow 'engagement')|Out-Null;& (Join-Path $root 'automation\Test-EngagementFitStandard.ps1') -Path (Join-Path $implFlow 'engagement')|Out-Null
 & (Join-Path $root 'automation\New-SyntheticSetupPermissionsData.ps1') -Destination (Join-Path $implFlow 'setup') -Profile implementation|Out-Null;& (Join-Path $root 'automation\Test-SetupPermissionsData.ps1') -Path (Join-Path $implFlow 'setup')|Out-Null
 & (Join-Path $root 'automation\New-SyntheticUatTrainingDefects.ps1') -Destination (Join-Path $implFlow 'uat') -Profile implementation|Out-Null;& (Join-Path $root 'automation\Test-UatTrainingDefects.ps1') -Path (Join-Path $implFlow 'uat')|Out-Null
 & (Join-Path $root 'automation\New-SyntheticCutoverOperationsHandover.ps1') -Destination (Join-Path $implFlow 'operations') -Profile implementation|Out-Null;& (Join-Path $root 'automation\Test-CutoverOperationsHandover.ps1') -Path (Join-Path $implFlow 'operations')|Out-Null;Assert-Exit 'PILOT_IMPLEMENTATION_FLOW_FAILED';$implRestored=Backup-Restore-Pilot 'implementation' $impl
 & (Join-Path $root 'automation\Test-EngagementFitStandard.ps1') -Path (Join-Path $implRestored 'pilot-evidence\engagement')|Out-Null;& (Join-Path $root 'automation\Test-SetupPermissionsData.ps1') -Path (Join-Path $implRestored 'pilot-evidence\setup')|Out-Null;& (Join-Path $root 'automation\Test-UatTrainingDefects.ps1') -Path (Join-Path $implRestored 'pilot-evidence\uat')|Out-Null;& (Join-Path $root 'automation\Test-CutoverOperationsHandover.ps1') -Path (Join-Path $implRestored 'pilot-evidence\operations')|Out-Null
 $support=Join-Path $temp 'support-only';Install-Pilot 'support-only' $support;$supportFlow=Join-Path $support 'pilot-evidence';New-Item -ItemType Directory $supportFlow|Out-Null
 & (Join-Path $root 'automation\New-SyntheticUatTrainingDefects.ps1') -Destination (Join-Path $supportFlow 'support-quality') -Profile support-only|Out-Null;& (Join-Path $root 'automation\Test-UatTrainingDefects.ps1') -Path (Join-Path $supportFlow 'support-quality')|Out-Null
 & (Join-Path $root 'automation\New-SyntheticCutoverOperationsHandover.ps1') -Destination (Join-Path $supportFlow 'support-handover') -Profile support-only|Out-Null;& (Join-Path $root 'automation\Test-CutoverOperationsHandover.ps1') -Path (Join-Path $supportFlow 'support-handover')|Out-Null;Assert-Exit 'PILOT_SUPPORT_FLOW_FAILED';$supportRestored=Backup-Restore-Pilot 'support-only' $support
 & (Join-Path $root 'automation\Test-UatTrainingDefects.ps1') -Path (Join-Path $supportRestored 'pilot-evidence\support-quality')|Out-Null;& (Join-Path $root 'automation\Test-CutoverOperationsHandover.ps1') -Path (Join-Path $supportRestored 'pilot-evidence\support-handover')|Out-Null
 & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'automation\Test-WorkspaceUpgrade.ps1')|Out-Null;Assert-Exit 'PILOT_UPGRADE_FAILED';& (Join-Path $PSScriptRoot 'Test-SpectraSemVer.ps1')|Out-Null
 $docs=@('notes\spectra-engagement-fit-standard-operator.md','notes\spectra-setup-permissions-data-quickstart.md','notes\spectra-uat-training-defects-quickstart.md','notes\spectra-cutover-operations-handover-quickstart.md','notes\spectra-backup-restore-operator.md','notes\spectra-workspace-upgrades.md');foreach($rel in $docs){$p=Join-Path $root $rel;if(-not(Test-Path $p -PathType Leaf)-or(Get-Item $p).Length-lt40){throw "PILOT_DOCUMENTATION_UNPROVEN:$rel"};$text=Get-Content $p -Raw;if($text-notmatch'(?i)(Prüf|Schritt|Workspace|Betrieb|Sicherung|Upgrade|Cutover)'){throw "PILOT_DOCUMENTATION_UNPROVEN:$rel"}}
 $evidence=[ordered]@{schema_version=1;product_id='spectra';release_version=$version;release_tag=$tag;tag_commit=$tagCommit;simulation_boundary='synthetic_non_production';implementation=[ordered]@{profile='implementation';install='PASS';domain_flow='PASS';backup_restore='PASS';read_only_validation='PASS';status='PASS'};support_only=[ordered]@{profile='support-only';install='PASS';domain_flow='PASS';backup_restore='PASS';read_only_validation='PASS';status='PASS'};upgrade=[ordered]@{status='PASS';negative_cases=2};recovery=[ordered]@{status='PASS';negative_cases=3};documentation=[ordered]@{status='PASS';files_checked=$docs.Count;language='de'};open_product_p1=0;open_product_p2=0;rc_decision='GO';known_limits=@('Piloten sind vollständig synthetisch und keine Kundenevidence','RC-Veröffentlichung benötigt einen getrennten Release-Gate')}
 $out=if($EvidencePath){[IO.Path]::GetFullPath($EvidencePath)}else{Join-Path $temp 'v1-pilot-evidence.json'};$parent=Split-Path $out -Parent;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Force $parent|Out-Null};[IO.File]::WriteAllText($out,(($evidence|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));& (Join-Path $PSScriptRoot 'Test-SpectraV1PilotEvidence.ps1') -Path $out -ProductRoot $root|Out-Null;Write-Host 'PASS: Implementation- und Support-only-Pilot, Upgrade, Recovery, Dokumentation und RC-Gate.'
}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
