$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$sandbox=Join-Path $env:TEMP ('spectra-bound-init-'+[guid]::NewGuid().ToString('N'));$fixture=Join-Path $sandbox 'repo';$version='9.7.0-alpha.1'
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function New-Answers([string]$Profile){[ordered]@{mode='new';project_id="PRJ-BOUND-$($Profile.ToUpperInvariant())";project_name="Synthetisches gebundenes Projekt $Profile";profile=$Profile;language='de-DE';processes=@('finance','p2p','o2c');collaboration='portable-atlassian';project_space_id="SPACE-BOUND-$($Profile.ToUpperInvariant())";project_space_title='Gebundener Projektbereich';referenced_spaces_path=$null;ticket_strategy='spectra-standard';ticket_provider='jira';ticket_mapping_version='1.0.0';ticket_mapping_path=$null;blueprints=@('BPC-CONFLUENCE-PROJECT','BPC-JIRA-PROJECT','BPC-METADATA');onboarding_source_path=$null}}
function Expect([string]$Name,[string]$Pattern,[scriptblock]$Run){try{& $Run;throw "EXPECTED_BOUND_INIT_FAILURE_NOT_RAISED:$Name"}catch{if($_.Exception.Message-notmatch$Pattern){throw "BOUND_INIT_NEGATIVE_MISMATCH:${Name}:$($_.Exception.Message)"}}}
try{
  New-Item -ItemType Directory -Path $fixture -Force|Out-Null
  foreach($rel in @('AGENTS.md','README.md','automation','catalogs','contract','examples\minimal-contract','schemas','skills','tests\invalid','release')){$src=Join-Path $root $rel;$dst=Join-Path $fixture $rel;$parent=Split-Path -Parent $dst;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};Copy-Item $src $dst -Recurse -Force}
  git -C $fixture init -b main|Out-Null;git -C $fixture config core.autocrlf false;git -C $fixture config user.email 'spectra-fixture@example.invalid';git -C $fixture config user.name 'Spectra Fixture';git -C $fixture remote add origin 'https://github.com/sivla/BCProjectOS.git';git -C $fixture add -A;git -C $fixture commit -m source|Out-Null;git -C $fixture checkout -- .;$source=(git -C $fixture rev-parse HEAD).Trim()
  powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $fixture 'automation\New-ReleaseCandidate.ps1') -Version $version -ReleaseDate 2026-07-12 -SourceCommit $source|Out-Null;git -C $fixture add release/versions/$version;git -C $fixture commit -m candidate|Out-Null
  $answersPath=Join-Path $sandbox 'answers.json';Write-Json $answersPath (New-Answers 'implementation');$candidateTarget=Join-Path $sandbox 'candidate-target'
  Expect 'candidate' 'SPECTRA_DELEGATE_FAILED:init:INSTALLABLE_MANIFEST_CONTRACT_INVALID' {& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace $candidateTarget -Guided -AnswersPath $answersPath -Apply -Profile implementation -Version $version -CustomerAlias 'synthetic-project' -ProductRoot $fixture|Out-Null}
  if(Test-Path $candidateTarget){throw 'BOUND_INIT_CANDIDATE_LEFT_TARGET'}
  powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $fixture 'automation\Promote-ReleaseCandidate.ps1') -RepositoryRoot $fixture -Version $version -SyntheticRepository|Out-Null
  $workspace=Join-Path $sandbox 'workspace';$applied=& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace $workspace -Guided -AnswersPath $answersPath -Apply -Profile implementation -Version $version -CustomerAlias 'synthetic-project' -ProductRoot $fixture|ConvertFrom-Json
  if(-not$applied.writes_performed-or-not(Test-Path (Join-Path $workspace 'workspace.yaml'))-or-not(Test-Path (Join-Path $workspace 'collaboration\pages\00 Support.md'))-or-not(Test-Path (Join-Path $workspace 'PROJECT-INIT.md'))){throw 'BOUND_INIT_OUTPUT_INCOMPLETE'}
  $validated=& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command validate -Workspace $workspace -ProductRoot $fixture|ConvertFrom-Json;if($validated.status-ne'VALIDATED'-or$validated.delegate-ne'Test-CustomerWorkspace.ps1'){throw 'BOUND_INIT_VALIDATION_ROUTE_INVALID'}
  Expect 'missing-binding' 'SPECTRA_DELEGATE_FAILED:init:SPECTRA_INIT_BINDING_REQUIRED' {& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace (Join-Path $sandbox 'missing-binding') -Guided -AnswersPath $answersPath -Apply|Out-Null}
  $before=(Get-FileHash (Join-Path $workspace 'workspace.yaml')).Hash;Expect 'existing-target' 'SPECTRA_DELEGATE_FAILED:init:BOUND_INIT_DESTINATION_EXISTS' {& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace $workspace -Guided -AnswersPath $answersPath -Apply -Profile implementation -Version $version -CustomerAlias 'synthetic-project' -ProductRoot $fixture|Out-Null};if((Get-FileHash (Join-Path $workspace 'workspace.yaml')).Hash-ne$before){throw 'BOUND_INIT_EXISTING_TARGET_MUTATED'}
  $supportPath=Join-Path $sandbox 'support-answers.json';Write-Json $supportPath (New-Answers 'support-only');Expect 'profile-mismatch' 'SPECTRA_DELEGATE_FAILED:init:BOUND_INIT_PROFILE_MISMATCH' {& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace (Join-Path $sandbox 'profile-mismatch') -Guided -AnswersPath $supportPath -Apply -Profile implementation -Version $version -CustomerAlias 'synthetic-project' -ProductRoot $fixture|Out-Null}
  git -C $fixture tag -d "spectra-v$version"|Out-Null;$missingTag=Join-Path $sandbox 'missing-tag';Expect 'missing-tag' 'SPECTRA_DELEGATE_FAILED:init:INSTALLABLE_TAG_MISSING' {& (Join-Path $root 'automation\Invoke-Spectra.ps1') -Command init -Workspace $missingTag -Guided -AnswersPath $answersPath -Apply -Profile implementation -Version $version -CustomerAlias 'synthetic-project' -ProductRoot $fixture|Out-Null};if(Test-Path $missingTag){throw 'BOUND_INIT_MISSING_TAG_LEFT_TARGET'}
  Write-Host 'PASS: Releasegebundener Guided Init ist atomar; Candidate, Binding, Profil, Ziel und Tag werden fail-closed geprüft.'
}finally{if(Test-Path $sandbox){Remove-Item $sandbox -Recurse -Force -ErrorAction SilentlyContinue}}
