[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$Path)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0;$file=Join-Path ([IO.Path]::GetFullPath($Path)) 'cutover-operations-handover.json';if(-not(Test-Path $file -PathType Leaf)){throw 'OPS_RECORD_MISSING'};$before=(Get-FileHash $file -Algorithm SHA256).Hash;$x=Get-Content $file -Raw|ConvertFrom-Json
. (Join-Path $PSScriptRoot 'Spectra.JsonSchema.ps1');$s=Get-Content (Join-Path $PSScriptRoot '..\schemas\cutover-operations-handover.schema.json') -Raw|ConvertFrom-Json;try{Test-SpectraJsonSchema -Value $x -Schema $s -RootSchema $s -Path root}catch{throw 'OPS_SCHEMA_INVALID'}
$roles=@($x.roles.id);$ev=@($x.evidence.id);$taskIds=@($x.cutover_tasks.id);$all=@($roles)+@($ev)+@($taskIds)+@($x.hypercare_days.id)+@($x.hypercare_days.issues.id)+@($x.mock_cutover.id,$x.go_live_gate.id,$x.restart_plan.id,$x.support_acceptance.id,$x.handover.id);if(@($all|Sort-Object -Unique).Count-ne$all.Count){throw 'OPS_DUPLICATE_ID'}
$seq=@($x.cutover_tasks|Sort-Object sequence);for($i=0;$i-lt$seq.Count;$i++){if([int]$seq[$i].sequence-ne$i+1){throw 'CUTOVER_SEQUENCE_INVALID'};if($seq[$i].owner_role-notin$roles-or@($seq[$i].evidence_refs|Where-Object{$_-notin$ev}).Count){throw 'OPS_REFERENCE_UNKNOWN'};if($i-eq0-and@($seq[$i].depends_on).Count){throw 'CUTOVER_DEPENDENCY_INVALID'};if($i-gt0-and($seq[$i-1].id-notin@($seq[$i].depends_on))){throw 'CUTOVER_DEPENDENCY_INVALID'}}
if(Compare-Object ($taskIds|Sort-Object) (@($x.mock_cutover.task_refs)|Sort-Object)){throw 'MOCK_CUTOVER_INCOMPLETE'};if($x.mock_cutover.status-ne'passed'-or@($x.mock_cutover.evidence_refs|Where-Object{$_-notin$ev}).Count){throw 'MOCK_CUTOVER_INCOMPLETE'}
if($x.go_live_gate.owner_role-notin$roles-or@($x.go_live_gate.evidence_refs|Where-Object{$_-notin$ev}).Count){throw 'OPS_REFERENCE_UNKNOWN'};if($x.go_live_gate.decision-in@('GO','GO_WITH_CONDITIONS')-and(-not$x.go_live_gate.criteria_met-or[int]$x.go_live_gate.open_p1-gt0-or[int]$x.go_live_gate.open_p2-gt0)){throw 'GO_LIVE_OPEN_HIGH_PRIORITY'}
$days=@($x.hypercare_days);for($i=0;$i-lt$days.Count;$i++){if($days[$i].owner_role-notin$roles-or$days[$i].daily_evidence_ref-notin$ev){throw 'OPS_REFERENCE_UNKNOWN'};if($i-gt0-and[datetime]$days[$i].day-le[datetime]$days[$i-1].day){throw 'HYPERCARE_CHRONOLOGY_INVALID'};foreach($issue in $days[$i].issues){if($issue.retest_evidence_ref-notin$ev){throw 'HYPERCARE_RETEST_EVIDENCE_MISSING'};if($issue.priority-in@('P1','P2')-and$issue.status-ne'closed'-and$days[-1].status-eq'closed'){throw 'HYPERCARE_OPEN_HIGH_PRIORITY'}}}
if($x.restart_plan.owner_role-notin$roles-or$x.restart_plan.backup_evidence_ref-notin$ev-or@($x.restart_plan.abort_criteria).Count-eq0-or@($x.restart_plan.resume_steps).Count-eq0){throw 'RESTART_RECOVERY_BINDING_MISSING'}
$issues=@($x.hypercare_days.issues.id);if($x.support_acceptance.owner_role-notin$roles-or@($x.support_acceptance.backlog_refs|Where-Object{$_-notin$issues}).Count-or@($x.support_acceptance.evidence_refs|Where-Object{$_-notin$ev}).Count){throw 'SUPPORT_ACCEPTANCE_INVALID'}
if(-not$x.handover.hypercare_exit-or$x.handover.support_acceptance_ref-ne$x.support_acceptance.id-or@($x.handover.evidence_refs|Where-Object{$_-notin$ev}).Count-or$x.handover.decision-ne'ACCEPTED'){throw 'HANDOVER_INCOMPLETE'};if([int]$x.handover.open_p1-gt0-or[int]$x.handover.open_p2-gt0){throw 'HANDOVER_OPEN_HIGH_PRIORITY'}
$raw=Get-Content $file -Raw;if($raw-match'(?i)(credential_marker|tenant_marker|customer_content_marker|universaarl|uabc)'){throw 'OPS_CUSTOMER_OR_SECRET_MARKER'};if((Get-FileHash $file -Algorithm SHA256).Hash-ne$before){throw 'OPS_VALIDATOR_MUTATED_SOURCE'};Write-Host 'PASS: Cutover, Hypercare, Restart, Support und Handover sind konsistent.'
